---
controller_credential_types:
- name: Chef Server Admin User
  description: Credential type for Chef Server Admin User
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Admin Username
      help_text: Username for the initial admin user in Chef Automate/Infra Server
    - id: password
      type: string
      label: Admin Password
      secret: true
      help_text: Password for the initial admin user in Chef Automate/Infra Server
    - id: organization
      type: string
      label: Chef Organization
      help_text: Organization name to create in Chef Infra Server
    required:
    - username
    - password
    - organization
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      organization: !unsafe '{{ organization }}'
