---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Set vm.max_map_count kernel parameter
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ chef_automate_vm_max_map_count }}"
    state: present
    reload: true
  become: true
- name: Set vm.dirty_expire_centisecs kernel parameter
  ansible.posix.sysctl:
    name: vm.dirty_expire_centisecs
    value: "{{ chef_automate_vm_dirty_expire_centisecs }}"
    state: present
    reload: true
  become: true
