---
controller_credential_types:
- name: Chef User Credentials
  description: Credential type for Chef User Credentials
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Chef Username
      help_text: Username for the initial Chef user account
    - id: password
      type: string
      label: Chef User Password
      secret: true
      help_text: Password for the initial Chef user account
    - id: email
      type: string
      label: Chef User Email
      help_text: Email address for the initial Chef user account
    - id: full_name
      type: string
      label: Chef User Full Name
      help_text: Full name for the initial Chef user account
    - id: organization_name
      type: string
      label: Chef Organization Name
      help_text: Name of the Chef organization to create
    - id: organization_full_name
      type: string
      label: Chef Organization Full Name
      help_text: Full name of the Chef organization to create
    required:
    - username
    - password
    - email
    - organization_name
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      email: !unsafe '{{ email }}'
      full_name: !unsafe '{{ full_name }}'
      organization_name: !unsafe '{{ organization_name }}'
      organization_full_name: !unsafe '{{ organization_full_name }}'
