---
- name: Save user PEM file
  ansible.builtin.debug:
    msg: User PEM file created at {{ automate_deploy_user_pem_path }}
- name: Save org validator PEM file
  ansible.builtin.debug:
    msg: Organization validator PEM file created at {{ automate_deploy_org_validator_pem_path }}
