---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - curl
      - gzip
    state: present
  become: true
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: "{{ chef_automate_cli_path }}"
    mode: "0755"
  register: download_result
- name: Extract Chef Automate CLI if compressed
  ansible.builtin.shell:
    cmd: gunzip -c {{ chef_automate_cli_path }} > {{ chef_automate_cli_path }}.extracted && mv {{ chef_automate_cli_path }}.extracted {{ chef_automate_cli_path
      }}
  args:
    creates: "{{ chef_automate_cli_path }}.extracted"
  when: download_result.changed and chef_automate_cli_url is search('\.zip$|\.gz$')
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: "{{ chef_automate_cli_path }}"
    mode: "0755"
    state: file
  become: true
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: "{{ chef_automate_cli_path }} deploy --product automate --product infra-server --accept-terms-and-mlsa={{ chef_automate_accept_terms | lower }}"
  args:
    creates: /hab
  become: true
  register: deploy_result
  changed_when: deploy_result.rc == 0
  failed_when: deploy_result.rc != 0
- name: Wait for Chef Server CLI to be available
  ansible.builtin.wait_for:
    path: /usr/bin/chef-server-ctl
    timeout: 300
    sleep: 10
  become: true
  tags: molecule-notest
