---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Ensure hostname is in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: ^127.0.0.1\s+{{ chef_automate_hostname }}$
    line: 127.0.0.1 {{ chef_automate_hostname }}
    state: present
  become: true
- name: Set vm.max_map_count kernel parameter
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    sysctl_set: true
    reload: true
  become: true
  notify: reload sysctl
- name: Set vm.dirty_expire_centisecs kernel parameter
  sysctl:
    name: vm.dirty_expire_centisecs
    value: "20000"
    state: present
    sysctl_set: true
    reload: true
  become: true
  notify: reload sysctl
