---
controller_credentials:
- name: Chef User Credentials - chef_automate_deployment
  description: Credentials for Chef Automate and Chef Infra Server user creation
  organization: Default
  credential_type: Chef User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
