---
- name: Set system configuration
  ansible.builtin.include_tasks: system_config.yml
- name: Install Chef Automate CLI
  ansible.builtin.include_tasks: install_cli.yml
- name: Check if Chef Server is already deployed
  ansible.builtin.stat:
    path: /etc/chef-automate/config.toml
  register: chef_server_config
  become: true
- name: Build Chef Server deploy command
  ansible.builtin.set_fact:
    chef_server_deploy_cmd: sudo ./{{ chef_automate_cli_path | basename }} deploy --product infra-server --accept-terms-and-mlsa={{
      chef_automate_accept_terms_and_mlsa | lower }}
- name: Deploy Chef Infra Server
  ansible.builtin.command:
    cmd: "{{ chef_server_deploy_cmd }}"
  args:
    creates: /etc/chef-automate/config.toml
  become: true
  register: deploy_result
  changed_when: deploy_result.rc == 0
  when: not chef_server_config.stat.exists
- name: Set up Chef users and organizations
  ansible.builtin.include_tasks: setup_users_orgs.yml
