---
- name: Create Chef user
  ansible.builtin.command:
    cmd: sudo chef-server-ctl user-create {{ username }} "{{ full_name }}" {{ email }} "{{ password }}" --filename {{ chef_automate_user_key_path }}/{{ username
      }}.pem
  args:
    creates: "{{ chef_automate_user_key_path }}/{{ username }}.pem"
  become: true
  register: create_user_result
  changed_when: create_user_result.rc == 0
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: sudo chef-server-ctl org-create {{ org_name }} "{{ org_full_name }}" --association_user {{ username }} --filename {{ chef_automate_org_key_path }}/{{
      org_name }}-validator.pem
  args:
    creates: "{{ chef_automate_org_key_path }}/{{ org_name }}-validator.pem"
  become: true
  register: create_org_result
  changed_when: create_org_result.rc == 0
