---
controller_credential_types:
- name: Chef Automate Admin User
  description: Credential type for Chef Automate Admin User
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Admin Username
      help_text: Username for the initial admin user in Chef Automate/Infra Server
    - id: password
      type: string
      label: Admin Password
      secret: true
      help_text: Password for the initial admin user in Chef Automate/Infra Server
    - id: key_file_path
      type: string
      label: User Key File Path
      help_text: Path where the user's authentication key file will be saved
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      key_file_path: !unsafe '{{ key_file_path }}'
- name: Chef Organization Validator
  description: Credential type for Chef Organization Validator
  kind: cloud
  inputs:
    fields:
    - id: organization_name
      type: string
      label: Organization Name
      help_text: Name of the Chef organization to create
    - id: validator_key_path
      type: string
      label: Validator Key File Path
      help_text: Path where the organization validator key file will be saved
    required:
    - organization_name
  injectors:
    extra_vars:
      organization_name: !unsafe '{{ organization_name }}'
      validator_key_path: !unsafe '{{ validator_key_path }}'
