---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - curl
      - jq
      - tar
    state: present
  become: true
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: "chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa=true "
  args:
    creates: /hab/sup/default/data/services.dat
  become: true
  register: deploy_result
  changed_when: deploy_result.rc == 0
- name: Wait for Chef Automate to be fully operational
  ansible.builtin.uri:
    url: https://localhost/api/v0/auth/version
    validate_certs: false
    status_code: 200
  register: automate_status
  until: automate_status.status == 200
  retries: 30
  delay: 10
  ignore_errors: true
  tags: molecule-notest
- name: Wait for Chef Infra Server to be fully operational
  ansible.builtin.uri:
    url: https://localhost/_status
    validate_certs: false
    status_code: 200
  register: infra_status
  until: infra_status.status == 200
  retries: 30
  delay: 10
  ignore_errors: true
  tags: molecule-notest
