---
controller_credentials:
- name: Chef Automate Admin User - chef_automate_deployment
  description: Credential for chef_automate_deployment
  organization: Default
  credential_type: Chef Automate Admin User
  update_secrets: true
  inputs:
    username: '{{ username }}'
    user_email: '{{ user_email }}'
    user_password: '{{ vault_user_password }}'
