---
controller_credential_types:
- name: Chef Automate Admin User
  description: Credential type for Chef Automate Admin User
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Admin Username
      help_text: Username for the initial admin user of Chef Automate and Chef Infra
        Server
    - id: password
      type: string
      label: Admin Password
      secret: true
      help_text: Password for the initial admin user of Chef Automate and Chef Infra
        Server
    - id: full_name
      type: string
      label: Full Name
      help_text: Full name for the initial admin user
    - id: email
      type: string
      label: Email Address
      help_text: Email address for the initial admin user
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      full_name: !unsafe '{{ full_name }}'
      email: !unsafe '{{ email }}'
