---
controller_credentials:
- name: Chef User Credentials - chef_automate_deploy
  description: Credential for chef_automate_deploy
  organization: Default
  credential_type: Chef User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    user_full_name: '{{ user_full_name }}'
    user_email: '{{ user_email }}'
    organization_name: '{{ organization_name }}'
