---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Configure system for Chef Automate
  ansible.builtin.include_tasks: system_config.yml
- name: Deploy Chef Automate with Infra Server
  ansible.builtin.include_tasks: install_automate.yml
  when: deploy_automate | bool or deploy_infra_server | bool
- name: Setup Chef users and organizations
  ansible.builtin.include_tasks: setup_users_orgs.yml
  when: deploy_automate | bool or deploy_infra_server | bool
