---
- name: Ensure Apache is installed
  ansible.builtin.package:
    name: apache2
    state: present
  become: true
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: /etc/apache2/mods-available/ssl.conf
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol -all +TLSv1.2
  notify:
    - Restart apache2
