---
- name: Restart Chef Automate
  ansible.builtin.command:
    cmd: chef-automate restart
  become: true
  listen: restart chef automate
  changed_when: true
  register: chef_automate_restart
  failed_when: chef_automate_restart.rc != 0 and "already running" not in chef_automate_restart.stderr
- name: Restart Chef Infra Server
  ansible.builtin.command:
    cmd: chef-server-ctl restart
  become: true
  listen: restart chef server
  changed_when: true
  register: chef_server_restart
  failed_when: chef_server_restart.rc != 0 and "already running" not in chef_server_restart.stderr
