---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ chef_hostname }}"
  become: true
- name: Set vm.max_map_count
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ chef_vm_max_map_count }}"
    state: present
    reload: true
  become: true
- name: Set vm.dirty_expire_centisecs
  ansible.posix.sysctl:
    name: vm.dirty_expire_centisecs
    value: "{{ chef_vm_dirty_expire_centisecs }}"
    state: present
    reload: true
  become: true
- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - curl
      - gzip
    state: present
  become: true
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: "{{ ansible_env.HOME }}/chef-automate.zip"
    mode: "0644"
  register: chef_automate_download
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: set -o pipefail && gunzip - < chef-automate.zip > chef-automate && chmod +x chef-automate
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/chef-automate"
- name: Deploy Chef Infra Server only
  ansible.builtin.command:
    cmd: ./chef-automate deploy --product infra-server --accept-terms-and-mlsa={{ chef_accept_terms_and_mlsa | lower }}
    creates: /hab
  args:
    chdir: "{{ ansible_env.HOME }}"
  become: true
  register: chef_server_deploy
  changed_when: chef_server_deploy.rc == 0
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create {{ username }} "{{ user_full_name }}" {{ user_email }} "{{ user_password }}" --filename {{ chef_user_filename }}
    creates: "{{ ansible_env.HOME }}/{{ chef_user_filename }}"
  args:
    chdir: "{{ ansible_env.HOME }}"
  become: true
  register: chef_user_create
  changed_when: chef_user_create.rc == 0
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create {{ chef_org_name }} "{{ chef_org_long_name }}" --association_user {{ username }} --filename {{ chef_org_filename }}
    creates: "{{ ansible_env.HOME }}/{{ chef_org_filename }}"
  args:
    chdir: "{{ ansible_env.HOME }}"
  become: true
  register: chef_org_create
  changed_when: chef_org_create.rc == 0
