---
- name: Ensure Apache is installed
  ansible.builtin.package:
    name: "{{ apache_service_name }}"
    state: present
- name: Ensure SSH server is installed
  ansible.builtin.package:
    name: "{{ ssh_service_name }}"
    state: present
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: "{{ apache_ssl_conf_path }}"
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol -all +TLSv1.2
  notify:
    - Restart apache2
    - Restart sshd
