---
- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml
  tags:
    - install
- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
  tags:
    - configure
- name: Include security tasks
  ansible.builtin.include_tasks: secure.yml
  tags:
    - secure
