---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    username: molecule_user
    full_name: Molecule Test User
    email: molecule@example.com
    password: molecule_password
    org_name: molecule_org
    org_full_name: Molecule Test Organization
    chef_automate_hostname: molecule.chef.lab
    chef_automate_user_pem_path: molecule_user.pem
    chef_automate_org_pem_path: molecule_org-validator.pem
    chef_automate_products:
      - automate
      - infra-server

  tasks:
    # Create directories that would be created or modified by the role
    - name: Create expected directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /tmp/molecule_test/etc
        - /tmp/molecule_test/hab
        - /tmp/molecule_test/tmp

    # Simulate hostname file
    - name: Create hostname file
      ansible.builtin.copy:
        content: "{{ chef_automate_hostname }}"
        dest: /tmp/molecule_test/etc/hostname
        mode: "0644"

    # Simulate kernel parameters
    - name: Create sysctl settings file
      ansible.builtin.copy:
        content: |
          vm.max_map_count = 262144
          vm.dirty_expire_centisecs = 20000
        dest: /tmp/molecule_test/etc/sysctl.d/99-chef-automate.conf
        mode: "0644"

    # Simulate Chef Automate CLI download
    - name: Create Chef Automate CLI file
      ansible.builtin.file:
        path: /tmp/molecule_test/tmp/chef-automate
        state: touch
        mode: "0755"

    # Simulate Chef Automate deployment marker
    - name: Create Chef Automate deployment marker
      ansible.builtin.file:
        path: /tmp/molecule_test/hab/sup
        state: directory
        mode: "0755"

    # Simulate user PEM file
    - name: Create user PEM file
      ansible.builtin.copy:
        content: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAu7YvQeKSGFwdNT5deVTSGnLJQXQRYDr5hBMRqBfmrJ5yZKkG
          molecule_user_pem_content
          -----END RSA PRIVATE KEY-----
        dest: /tmp/molecule_test/{{ chef_automate_user_pem_path }}
        mode: "0600"

    # Simulate organization PEM file
    - name: Create organization PEM file
      ansible.builtin.copy:
        content: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAu7YvQeKSGFwdNT5deVTSGnLJQXQRYDr5hBMRqBfmrJ5yZKkG
          molecule_org_pem_content
          -----END RSA PRIVATE KEY-----
        dest: /tmp/molecule_test/{{ chef_automate_org_pem_path }}
        mode: "0600"