---
apache_version: 2.4.41-4ubuntu3.10
apache_certs_dir: /etc/apache2/certs
apache_sites_available_dir: /etc/apache2/sites-available
apache_ssl_protocol: -all +TLSv1.2
website_domain: myhost
website_doc_root: /var/www/helloworld
website_port: 443
