---
- name: Restart Chef Automate
  ansible.builtin.command:
    cmd: sudo ./chef-automate restart
  args:
    chdir: "{{ ansible_env.HOME }}"
  listen: restart chef automate
  register: restart_result
  changed_when: restart_result.rc == 0
  when:
    - chef_automate_cli_path is defined
    - chef_automate_cli_path | length > 0
