---
- name: Validate credential variables
  ansible.builtin.include_tasks:
    file: validate_credentials.yml
- name: Configure system for Chef Automate
  ansible.builtin.include_tasks:
    file: system_config.yml
- name: Install Chef Automate and Chef Infra Server
  ansible.builtin.include_tasks:
    file: install_automate.yml
- name: Setup Chef users and organizations
  ansible.builtin.include_tasks:
    file: setup_users_orgs.yml
