---
- name: Wait for Chef Automate services
  ansible.builtin.wait_for:
    host: localhost
    port: 443
    state: started
    timeout: 300
  tags: molecule-notest
- name: Wait for Chef Infra Server services
  ansible.builtin.wait_for:
    host: localhost
    port: 443
    state: started
    timeout: 300
  tags: molecule-notest
