---
chef_automate_hostname: chef-automate.example.com
chef_automate_vm_max_map_count: "262144"
chef_automate_vm_dirty_expire_centisecs: "20000"
chef_automate_version: latest
chef_automate_download_url: https://packages.chef.io/files/current/automate/latest/chef-automate_linux_amd64.zip
chef_automate_cli_url: "{{ chef_automate_download_url }}"
chef_automate_cli_path: /usr/local/bin/chef-automate
chef_automate_install_dir: /opt/chef-automate
chef_automate_config_file: "{{ chef_automate_install_dir }}/config.toml"
chef_automate_license: "{{ lookup('env', 'CHEF_AUTOMATE_LICENSE') }}"
chef_automate_accept_terms: "true"
chef_server_version: 14.0.65
chef_server_download_url: https://packages.chef.io/files/stable/chef-server/{{ chef_server_version }}/el/8/chef-server-core-{{ chef_server_version
  }}-1.el8.x86_64.rpm
chef_server_install_dir: /opt/chef-server
chef_user_name: admin
chef_user_full_name: Chef Administrator
chef_user_email: admin@example.com
chef_user_password: "{{ lookup('env', 'CHEF_ADMIN_PASSWORD') }}"
chef_user_key_file: /etc/chef/admin.pem
chef_org_name: example
chef_org_full_name: Example Organization
chef_org_validator_key_file: /etc/chef/example-validator.pem
