---
controller_credentials:
- name: Chef Admin User - chef_infrastructure_deployment
  description: Credentials for the Chef admin user account used during server deployment
  organization: Default
  credential_type: Chef Admin User
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
