---
- name: Ensure PEM file directories exist
  ansible.builtin.file:
    path: "{{ item | dirname | expanduser }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ chef_automate_user_pem_path }}"
    - "{{ chef_automate_org_pem_path }}"
  become: true
  when: ansible_user_id != 'root'
- name: Create Chef user
  ansible.builtin.command:
    cmd: 'chef-server-ctl user-create  {{ username }}  "{{ chef_automate_user_longname }}"  {{ chef_automate_user_email }}  "{{ password }}"  --filename {{ chef_automate_user_pem_path
      | expanduser }}

      '
  become: true
  args:
    creates: "{{ chef_automate_user_pem_path | expanduser }}"
- name: Create Chef organization
  ansible.builtin.command:
    cmd: 'chef-server-ctl org-create  {{ chef_automate_org_name }}  "{{ chef_automate_org_longname }}"  --association_user {{ username }}  --filename {{ chef_automate_org_pem_path
      | expanduser }}

      '
  become: true
  args:
    creates: "{{ chef_automate_org_pem_path | expanduser }}"
- name: Set proper permissions on user PEM file
  ansible.builtin.file:
    path: "{{ chef_automate_user_pem_path | expanduser }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
  become: true
  when: ansible_user_id != 'root'
- name: Set proper permissions on organization PEM file
  ansible.builtin.file:
    path: "{{ chef_automate_org_pem_path | expanduser }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
  become: true
  when: ansible_user_id != 'root'
