---
controller_credentials:
- name: Chef User Password - chef_automate_deployment
  description: Credentials for the initial Chef administrator user
  organization: Default
  credential_type: Chef User Password
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    email: '{{ email }}'
    full_name: '{{ full_name }}'
- name: Chef Organization - chef_automate_deployment
  description: Organization details for Chef Infra Server
  organization: Default
  credential_type: Chef Organization
  update_secrets: true
  inputs:
    organization_name: '{{ organization_name }}'
    organization_full_name: '{{ organization_full_name }}'
- name: Chef Server Configuration - chef_automate_deployment
  description: System configuration for Chef server deployment
  organization: Default
  credential_type: Chef Server Configuration
  update_secrets: true
  inputs:
    hostname: '{{ hostname }}'
