---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - unzip
      - curl
    state: present
  become: true
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: "{{ chef_automate_cli_path }}.zip"
    mode: "0644"
  register: download_result
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip - > {{ chef_automate_cli_path }} < {{ chef_automate_cli_path }}.zip && chmod +x {{ chef_automate_cli_path }}
  args:
    creates: "{{ chef_automate_cli_path }}"
  when: download_result is changed
- name: Deploy Chef Infra Server only
  ansible.builtin.command:
    cmd: "{{ chef_automate_cli_path }} deploy  --product infra-server  --accept-terms-and-mlsa={{ 'true' if chef_automate_accept_terms else 'false' }} "
  become: true
  args:
    creates: /hab
  register: deploy_result
  when: chef_automate_deploy_infra_server and not chef_automate_deploy_automate
- name: Wait for Chef Infra Server deployment to complete
  ansible.builtin.pause:
    seconds: 30
  when: deploy_result is changed
