---
- name: Check if SSH root login is disabled
  ansible.builtin.command:
    cmd: grep -i "PermitRootLogin" /etc/ssh/sshd_config
  register: ssh_root_login
  changed_when: false
  failed_when: false
  check_mode: false
- name: Check if openssh-server is installed
  ansible.builtin.package_facts:
    manager: auto
  register: package_facts
  check_mode: false
- name: Verify SSH root login is disabled
  ansible.builtin.assert:
    that:
      - "('openssh-server' not in ansible_facts.packages) or (ssh_root_login.rc != 0) or (ssh_root_login.stdout is search('PermitRootLogin no')) or (not ssh_root_login.stdout
        is search('PermitRootLogin yes'))\n"
    fail_msg: SSH root login is enabled. This violates security policy SRG-OS-000112, STIG ID RHEL-08-000227.
    success_msg: SSH root login is properly disabled or openssh-server is not installed.
  tags:
    - security
    - ssh
    - SRG-OS-000112
    - V-38607
    - SV-50408r1_rule
    - CAT_I
    - RHEL-08-000227
    - CCI-000774
