---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Configure system parameters
  ansible.builtin.include_tasks: system_config.yml
- name: Install Chef Automate
  ansible.builtin.include_tasks: install.yml
  when: chef_automate_deploy_automate | bool
- name: Setup user and organization
  ansible.builtin.include_tasks: user_org_setup.yml
  when: chef_automate_deploy_infra_server | bool
- name: Deploy Chef Server only (without Automate)
  ansible.builtin.include_tasks: deploy_chef_server.yml
  when: not chef_automate_deploy_automate | bool and chef_automate_deploy_infra_server | bool
