---
controller_credentials:
- name: PostgreSQL Database Credential - fastapi_tutorial
  description: PostgreSQL database credentials for FastAPI application connection
  organization: Default
  credential_type: PostgreSQL Database Credential
  update_secrets: true
  inputs:
    db_username: '{{ db_username }}'
    db_password: '{{ vault_db_password }}'
    db_host: '{{ db_host }}'
    db_name: '{{ db_name }}'
