---
controller_credentials:
- name: Chef Automation User - chef_and_ansible
  description: User credentials for Chef Automation and Chef Infra Server setup
  organization: Default
  credential_type: Chef Automation User
  update_secrets: true
  inputs:
    username: '{{ username }}'
    long_username: '{{ long_username }}'
    user_email: '{{ user_email }}'
    user_password: '{{ vault_user_password }}'
    org_name: '{{ org_name }}'
