---
controller_credentials:
- name: Chef Admin User Credentials - chef_automate_setup
  description: Credential for chef_automate_setup
  organization: Default
  credential_type: Chef Admin User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    email: '{{ email }}'
- name: Chef User PEM - chef_automate_setup
  description: Credential for chef_automate_setup
  organization: Default
  credential_type: Chef User PEM
  update_secrets: true
  inputs:
    user_key: '{{ vault_user_key }}'
    user_key_path: '{{ user_key_path }}'
- name: Chef Organization Validator PEM - chef_automate_setup
  description: Credential for chef_automate_setup
  organization: Default
  credential_type: Chef Organization Validator PEM
  update_secrets: true
  inputs:
    org_validator_key: '{{ vault_org_validator_key }}'
    org_validator_path: '{{ org_validator_path }}'
    org_name: '{{ org_name }}'
