---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - unzip
      - curl
    state: present
  become: true
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ automate_cli_url }}"
    dest: /tmp/chef-automate.zip
    mode: "0644"
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip - > chef-automate
    stdin: "{{ lookup('ansible.builtin.file', '/tmp/chef-automate.zip') }}"
    chdir: /tmp
    creates: /tmp/chef-automate
  args:
    executable: /bin/bash
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: /tmp/chef-automate
    mode: "0755"
- name: Deploy Chef Infra Server only
  ansible.builtin.command:
    cmd: ./chef-automate deploy --product infra-server --accept-terms-and-mlsa={{ automate_accept_terms_and_mlsa | lower }}
    chdir: /tmp
    creates: /etc/chef-automate/config.toml
  become: true
