---
- name: Ensure user home directory exists
  ansible.builtin.file:
    path: /home/{{ automate_username }}
    state: directory
    owner: "{{ automate_username }}"
    group: "{{ automate_username }}"
    mode: "0750"
  become: true
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create  {{ automate_username }}  {{ automate_user_fullname }}  {{ automate_user_email }}  "{{ user_password }}"  --filename
      /home/{{ automate_username }}/{{ automate_user_pem_filename }}
    creates: /home/{{ automate_username }}/{{ automate_user_pem_filename }}
  become: true
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create  {{ automate_org_name }}  "{{ automate_org_fullname }}"  --association_user {{ automate_username }}  --filename /home/{{
      automate_username }}/{{ automate_org_pem_filename }}
    creates: /home/{{ automate_username }}/{{ automate_org_pem_filename }}
  become: true
