---
apache_version: 2.4.41-4ubuntu3.10
apache_certs_dir: /etc/apache2/certs
apache_site_name: helloworld
apache_document_root: /var/www/helloworld
apache_ssl_cert_file: "{{ apache_certs_dir }}/apache.crt"
apache_ssl_key_file: "{{ apache_certs_dir }}/apache.key"
apache_ssl_csr_file: "{{ apache_certs_dir }}/apache.csr"
apache_ssl_common_name: myhost
