---
controller_credentials:
- name: Chef Server Deployment Credentials - apache_https_website
  description: Credentials used for Chef Server and Chef Automate deployment
  organization: Default
  credential_type: Chef Server Deployment Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Apache SSL Certificate - apache_https_website
  description: SSL certificate information for Apache HTTPS configuration
  organization: Default
  credential_type: Apache SSL Certificate
  update_secrets: true
  inputs:
    ssl_private_key: '{{ vault_ssl_private_key }}'
    ssl_certificate: '{{ ssl_certificate }}'
    ssl_common_name: '{{ ssl_common_name }}'
