---
- name: Restart apache
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: restarted
  become: true
- name: Restart sshd
  ansible.builtin.service:
    name: "{{ ssh_service_name }}"
    state: restarted
  become: true
