---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Set system hostname
  ansible.builtin.include_tasks: set_hostname.yml
- name: Configure kernel parameters
  ansible.builtin.include_tasks: configure_kernel.yml
- name: Install Chef Automate CLI
  ansible.builtin.include_tasks: install_cli.yml
- name: Check if Chef Automate is already deployed
  ansible.builtin.stat:
    path: /hab/sup
  register: hab_sup_dir
  become: true
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: ./chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa=true
    creates: /hab/sup
  become: true
  args:
    chdir: "{{ playbook_dir }}"
  when: automate_deploy_automate and automate_deploy_infra_server and not hab_sup_dir.stat.exists
- name: Deploy Chef Infra Server only
  ansible.builtin.include_tasks: deploy_chef_server.yml
  when: not automate_deploy_automate and automate_deploy_infra_server
- name: Create Chef user and organization
  ansible.builtin.include_tasks: create_user_org.yml
