---
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: "{{ chef_automate_cli_path }}.zip"
    mode: "0644"
  when: chef_server_only | bool
- name: Check if Chef Automate CLI already exists
  ansible.builtin.stat:
    path: "{{ chef_automate_cli_path }}"
  register: chef_automate_cli_stat
  when: chef_server_only | bool
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip -c {{ chef_automate_cli_path }}.zip > {{ chef_automate_cli_path }}
  when:
    - chef_server_only | bool
    - not chef_automate_cli_stat.stat.exists
  changed_when: true
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: "{{ chef_automate_cli_path }}"
    mode: "0755"
    state: file
  when: chef_server_only | bool
- name: Deploy Chef Infra Server only
  ansible.builtin.command:
    cmd: ./chef-automate deploy --product infra-server --accept-terms-and-mlsa={{ chef_automate_accept_terms_and_mlsa | lower }}
  become: true
  args:
    creates: /hab
  register: chef_server_deploy
  changed_when: chef_server_deploy.rc == 0
  when: chef_server_only | bool
- name: Display Chef Server deployment output
  ansible.builtin.debug:
    var: chef_server_deploy.stdout_lines
  when:
    - chef_server_only | bool
    - chef_server_deploy.stdout_lines is defined
