---
controller_credential_types:
- name: Chef Server User Authentication
  description: Credentials used to create and authenticate the initial admin user
    in Chef Server and Chef Automate
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for Chef Server/Automate admin account
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef Server/Automate admin account
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
