---
- name: Restart Chef Automate
  ansible.builtin.shell:
    cmd: chef-automate status | grep -q "not running" || chef-automate restart
  become: true
  listen: restart chef automate
  changed_when: true
- name: Restart Chef Server
  ansible.builtin.shell:
    cmd: chef-server-ctl status | grep -q "not running" || chef-server-ctl restart
  become: true
  listen: restart chef server
  changed_when: true
