---
controller_credential_types:
- name: Chef User Credentials
  description: Credential type for Chef User Credentials
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Chef user account username
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for the Chef user account
    - id: full_name
      type: string
      label: Full Name
      help_text: Full name for the Chef user account
    - id: email
      type: string
      label: Email Address
      help_text: Email address for the Chef user account
    required:
    - username
    - password
    - full_name
    - email
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      full_name: !unsafe '{{ full_name }}'
      email: !unsafe '{{ email }}'
- name: Chef Organization Configuration
  description: Credential type for Chef Organization Configuration
  kind: cloud
  inputs:
    fields:
    - id: org_name
      type: string
      label: Organization Name
      help_text: Short name for the Chef organization
    - id: org_full_name
      type: string
      label: Organization Full Name
      help_text: Full name for the Chef organization
    required:
    - org_name
    - org_full_name
  injectors:
    extra_vars:
      org_name: !unsafe '{{ org_name }}'
      org_full_name: !unsafe '{{ org_full_name }}'
- name: Chef User Key
  description: Credential type for Chef User Key
  kind: cloud
  inputs:
    fields:
    - id: user_key
      type: string
      label: User Key
      secret: true
      help_text: Authentication key for the Chef user
    required:
    - user_key
  injectors:
    extra_vars:
      user_key: !unsafe '{{ user_key }}'
- name: Chef Organization Validator Key
  description: Credential type for Chef Organization Validator Key
  kind: cloud
  inputs:
    fields:
    - id: validator_key
      type: string
      label: Organization Validator Key
      secret: true
      help_text: Authentication key for the Chef organization
    required:
    - validator_key
  injectors:
    extra_vars:
      validator_key: !unsafe '{{ validator_key }}'
