---
- name: Ensure key file directories exist
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ chef_user_key_path }}"
    - "{{ chef_org_validator_key_path }}"
  become: true
- name: Create Chef user
  ansible.builtin.command:
    cmd: 'chef-server-ctl user-create {{ username }} "{{ full_name }}" {{ email }} "{{ user_password }}" --filename {{ chef_user_key_path }}

      '
  args:
    creates: "{{ chef_user_key_path }}"
  become: true
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: 'chef-server-ctl org-create {{ org_name }} "{{ org_full_name }}" --association_user {{ username }} --filename {{ chef_org_validator_key_path }}

      '
  args:
    creates: "{{ chef_org_validator_key_path }}"
  become: true
