---
controller_credentials:
- name: Chef User Credentials - chef_automate_deploy
  description: Credential for chef_automate_deploy
  organization: Default
  credential_type: Chef User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    full_name: '{{ full_name }}'
    email: '{{ email }}'
- name: Chef User Key File - chef_automate_deploy
  description: Credential for chef_automate_deploy
  organization: Default
  credential_type: Chef User Key File
  update_secrets: true
  inputs:
    user_key_path: '{{ user_key_path }}'
    user_key_content: '{{ vault_user_key_content }}'
- name: Chef Organization Validator - chef_automate_deploy
  description: Credential for chef_automate_deploy
  organization: Default
  credential_type: Chef Organization Validator
  update_secrets: true
  inputs:
    org_short_name: '{{ org_short_name }}'
    org_full_name: '{{ org_full_name }}'
    org_validator_path: '{{ org_validator_path }}'
    org_validator_content: '{{ vault_org_validator_content }}'
