---
- name: Restart Chef Automate
  ansible.builtin.command:
    cmd: chef-automate restart
  listen: restart chef-automate
  ignore_errors: true
  become: true
- name: Restart Chef Infra Server
  ansible.builtin.command:
    cmd: chef-server-ctl restart
  listen: restart chef-server
  ignore_errors: true
  become: true
