---
- name: Create Chef Infra Server user
  ansible.builtin.command:
    cmd: 'chef-server-ctl user-create {{ username }} "{{ full_name }}" {{ email }} "{{ password }}" --filename {{ username }}.pem

      '
  args:
    creates: ~/{{ username }}.pem
  become: true
  no_log: true
- name: Create Chef Infra Server organization
  ansible.builtin.command:
    cmd: 'chef-server-ctl org-create {{ orgname }} "{{ longorgname }}" --association_user {{ username }} --filename {{ orgname }}-validator.pem

      '
  args:
    creates: ~/{{ orgname }}-validator.pem
  become: true
