---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Configure system for Chef Automate
  ansible.builtin.include_tasks: system_config.yml
- name: Install Chef Automate and Chef Infra Server
  ansible.builtin.include_tasks: install_automate.yml
- name: Setup Chef user and organization
  ansible.builtin.include_tasks: setup_user_org.yml
