---
- name: Ensure directory exists for PEM files
  ansible.builtin.file:
    path: "{{ chef_automate_user_pem_file | dirname }}"
    state: directory
    mode: "0755"
  when: chef_automate_user_pem_file | dirname != '.'
- name: Create Chef user
  ansible.builtin.command:
    cmd: 'sudo chef-server-ctl user-create {{ username }} "{{ user_full_name }}" {{ user_email }} "{{ password }}" --filename {{ chef_automate_user_pem_file }}

      '
  args:
    creates: "{{ chef_automate_user_pem_file }}"
  register: chef_user_create
  changed_when: chef_user_create.rc == 0
- name: Create Chef organization
  ansible.builtin.command:
    cmd: 'sudo chef-server-ctl org-create {{ organization_name }} "{{ organization_full_name }}" --association_user {{ username }} --filename {{ chef_automate_org_pem_file
      }}

      '
  args:
    creates: "{{ chef_automate_org_pem_file }}"
  register: chef_org_create
  changed_when: chef_org_create.rc == 0
