---
apache_version: 2.4.41-4ubuntu3.10
website_domain: myhost
ssl_cert_path: /etc/apache2/certs
website_root: /var/www/helloworld
website_title: Test Site
website_heading: Hello, world!
website_content: The site is up and running
