---
controller_credentials:
- name: Chef User Authentication - chef_deployment
  description: Credentials for Chef user account creation and authentication
  organization: Default
  credential_type: Chef User Authentication
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    email: '{{ email }}'
    full_name: '{{ full_name }}'
