- name: Converge
  hosts: all
  gather_facts: true
  tasks:
  - name: Create expected directories
    ansible.builtin.file:
      path: '{{ item }}'
      state: directory
      mode: '0755'
    loop:
    - /tmp/molecule_test/etc/chef-automate
    - /tmp/molecule_test/etc/systemd/system
    - /tmp/molecule_test/var/log/chef-automate
    - /tmp/molecule_test/var/opt/chef-automate
  - name: Create hostname file
    ansible.builtin.copy:
      content: '{{ chef_automate_hostname }}'
      dest: /tmp/molecule_test/etc/hostname
      mode: '0644'
  - name: Create sysctl configuration file
    ansible.builtin.copy:
      content: 'vm.max_map_count = 262144

        vm.dirty_expire_centisecs = 20000

        '
      dest: /tmp/molecule_test/etc/sysctl.d/99-chef-automate.conf
      mode: '0644'
  - name: Create Chef Automate CLI file
    ansible.builtin.copy:
      content: '#!/bin/bash echo ''Chef Automate CLI Mock'' '
      dest: /tmp/molecule_test/chef-automate
      mode: '0755'
  - name: Create Chef Automate config file
    ansible.builtin.copy:
      content: "# Chef Automate configuration file\n[global]\n  v1 = true\n[deployment]\n  products = [\"automate\", \"infra-server\"]\n"
      dest: /tmp/molecule_test/etc/chef-automate/config.toml
      mode: '0644'
  - name: Create Chef Automate service file
    ansible.builtin.copy:
      content: '[Unit]

        Description=Chef Automate

        After=network.target


        [Service]

        Type=simple

        ExecStart=/usr/bin/chef-automate-ctl start

        ExecStop=/usr/bin/chef-automate-ctl stop


        [Install]

        WantedBy=multi-user.target

        '
      dest: /tmp/molecule_test/etc/systemd/system/chef-automate.service
      mode: '0644'
  - name: Create Chef Server service file
    ansible.builtin.copy:
      content: '[Unit]

        Description=Chef Infra Server

        After=network.target


        [Service]

        Type=simple

        ExecStart=/usr/bin/chef-server-ctl start

        ExecStop=/usr/bin/chef-server-ctl stop


        [Install]

        WantedBy=multi-user.target

        '
      dest: /tmp/molecule_test/etc/systemd/system/chef-server.service
      mode: '0644'
  - name: Create user key file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY----- MOCK USER KEY -----END RSA PRIVATE KEY----- '
      dest: /tmp/molecule_test/{{ chef_automate_user.key_file }}
      mode: '0600'
  - name: Create organization validator key file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY----- MOCK ORG VALIDATOR KEY -----END RSA PRIVATE KEY----- '
      dest: /tmp/molecule_test/{{ chef_automate_org.key_file }}
      mode: '0600'
  - name: Create user list file
    ansible.builtin.copy:
      content: '{{ chef_automate_user.name }} '
      dest: /tmp/molecule_test/chef-server-users.txt
      mode: '0644'
  - name: Create organization list file
    ansible.builtin.copy:
      content: '{{ chef_automate_org.name }} '
      dest: /tmp/molecule_test/chef-server-orgs.txt
      mode: '0644'
