---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: configure_hostname | bool
  become: true
- name: Set vm.max_map_count kernel parameter
  community.general.sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_map_count }}"
    state: present
    reload: true
  become: true
  when: configure_kernel_parameters | bool
- name: Set vm.dirty_expire_centisecs kernel parameter
  community.general.sysctl:
    name: vm.dirty_expire_centisecs
    value: "{{ vm_dirty_expire_centisecs }}"
    state: present
    reload: true
  become: true
  when: configure_kernel_parameters | bool
