---
controller_credential_types:
- name: Chef Automation User
  description: Credential type for Chef Automation User
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for Chef Automate/Server authentication
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef Automate/Server authentication
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
