---
- name: Ensure SSH server is installed
  ansible.builtin.apt:
    name: openssh-server
    state: present
- name: Configure HTTPS website
  ansible.builtin.import_tasks: website_https.yml
- name: Apply POODLE vulnerability fix
  ansible.builtin.import_tasks: poodle_fix.yml
