---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Configure system settings
  ansible.builtin.include_tasks: system_config.yml
- name: Install Chef Automate
  ansible.builtin.include_tasks: install.yml
- name: Setup Chef Automate user and organization
  ansible.builtin.include_tasks: user_setup.yml
