---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Configure system for Chef Automate
  ansible.builtin.include_tasks: system_configuration.yml
- name: Install Chef Automate CLI
  ansible.builtin.include_tasks: install_cli.yml
- name: Deploy Chef Automate with Infra Server
  ansible.builtin.include_tasks: deploy_automate.yml
  when: "'automate' in chef_automate_products"
- name: Deploy Chef Infra Server only
  ansible.builtin.include_tasks: deploy_chef_server.yml
  when: "'automate' not in chef_automate_products and 'infra-server' in chef_automate_products"
- name: Create Chef users and organizations
  ansible.builtin.include_tasks: create_users_orgs.yml
