---
controller_credentials:
- name: Chef Admin User - deploy_automate
  description: Credential for deploy_automate
  organization: Default
  credential_type: Chef Admin User
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    first_name: '{{ first_name }}'
    last_name: '{{ last_name }}'
    email: '{{ email }}'
- name: Chef User PEM - deploy_automate
  description: Credential for deploy_automate
  organization: Default
  credential_type: Chef User PEM
  update_secrets: true
  inputs:
    user_pem: '{{ vault_user_pem }}'
- name: Chef Organization Validator - deploy_automate
  description: Credential for deploy_automate
  organization: Default
  credential_type: Chef Organization Validator
  update_secrets: true
  inputs:
    organization_name: '{{ organization_name }}'
    organization_full_name: '{{ organization_full_name }}'
    organization_validator_pem: '{{ vault_organization_validator_pem }}'
- name: Chef Automate Admin - deploy_automate
  description: Credential for deploy_automate
  organization: Default
  credential_type: Chef Automate Admin
  update_secrets: true
  inputs:
    admin_username: '{{ admin_username }}'
    admin_password: '{{ vault_admin_password }}'
