---
fastapi_tutorial_app_dir: /opt/fastapi-tutorial
fastapi_tutorial_app_user: root
fastapi_tutorial_app_group: root
fastapi_tutorial_app_port: 8000
fastapi_tutorial_git_repo: https://github.com/dibanez/fastapi_tutorial.git
fastapi_tutorial_git_branch: main
fastapi_tutorial_project_name: FastAPI Tutorial
fastapi_tutorial_api_version: 1.0.0
fastapi_tutorial_service_name: fastapi-tutorial
fastapi_tutorial_service_user: root
fastapi_tutorial_system_packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - postgresql
  - postgresql-contrib
  - libpq-dev
fastapi_tutorial_postgresql_service: postgresql
