---
- name: Wait for Chef Automate services
  ansible.builtin.pause:
    seconds: 30
- name: Wait for Chef Infra Server services
  ansible.builtin.pause:
    seconds: 30
- name: Set permissions on user key file
  ansible.builtin.file:
    path: "{{ chef_user_key_file }}"
    mode: "0600"
    state: file
- name: Set permissions on organization validator key file
  ansible.builtin.file:
    path: "{{ chef_org_validator_key_file }}"
    mode: "0600"
    state: file
