---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
- name: Restart fastapi tutorial service
  ansible.builtin.systemd:
    name: "{{ fastapi_tutorial_service_name }}"
    state: restarted
- name: Start fastapi tutorial service
  ansible.builtin.systemd:
    name: "{{ fastapi_tutorial_service_name }}"
    state: started
- name: Stop fastapi tutorial service
  ansible.builtin.systemd:
    name: "{{ fastapi_tutorial_service_name }}"
    state: stopped
