---
chef_automate_hostname: automate.chef.lab
chef_automate_username: jtonello
chef_automate_orgname: lab
chef_automate_longorgname: Chef Lab
chef_automate_userfilename: "{{ chef_automate_username }}.pem"
chef_automate_orgfilename: "{{ chef_automate_orgname }}-validator.pem"
