---
controller_credentials:
- name: Chef Server User Credentials - chef_automate_deployment
  description: Credentials used for creating Chef users and organizations
  organization: Default
  credential_type: Chef Server User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    user_email: '{{ user_email }}'
    user_full_name: '{{ user_full_name }}'
- name: Chef Organization Configuration - chef_automate_deployment
  description: Configuration for Chef organization setup
  organization: Default
  credential_type: Chef Organization Configuration
  update_secrets: true
  inputs:
    org_name: '{{ org_name }}'
    org_full_name: '{{ org_full_name }}'
