---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
- name: Install necessary packages
  ansible.builtin.apt:
    name: "{{ apache_package }}={{ apache_version }}"
    state: present
- name: Install curl, openssl, PyOpenSSL
  ansible.builtin.apt:
    pkg: "{{ additional_packages }}"
    state: present
- name: Create a directory for certs
  ansible.builtin.file:
    path: "{{ ssl_cert_dir }}"
    state: directory
    mode: "0640"
- name: Generate an openssl key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_key_path }}"
- name: Generate an openssl csr
  community.crypto.openssl_csr:
    path: "{{ ssl_csr_path }}"
    privatekey_path: "{{ ssl_key_path }}"
    common_name: "{{ ansible_hostname }}"
- name: Generate a self-signed openssl certificate
  community.crypto.openssl_certificate:
    path: "{{ ssl_cert_path }}"
    privatekey_path: "{{ ssl_key_path }}"
    csr_path: "{{ ssl_csr_path }}"
    provider: selfsigned
- name: Configure Hello World virtual host
  ansible.builtin.template:
    src: helloworld.conf.j2
    dest: /etc/apache2/sites-available/{{ website_name }}.conf
    mode: "0640"
    force: true
- name: Create the helloworld directory
  ansible.builtin.file:
    path: "{{ website_doc_root }}"
    state: directory
    mode: "0755"
- name: Deploy the Hello World website
  ansible.builtin.copy:
    src: index.html
    dest: "{{ website_doc_root }}/index.html"
    owner: root
    group: root
    mode: "0644"
    force: true
- name: Check if default site is enabled
  ansible.builtin.stat:
    path: /etc/apache2/sites-enabled/000-default.conf
  register: default_site
- name: Deactivate the default virtualhost
  ansible.builtin.command: a2dissite 000-default
  when: default_site.stat.exists
  changed_when: default_site.stat.exists
- name: Check if website is enabled
  ansible.builtin.stat:
    path: /etc/apache2/sites-enabled/{{ website_name }}.conf
  register: website_enabled
- name: Activate the virtualhost
  ansible.builtin.command: a2ensite {{ website_name }}
  notify:
    - Restart apache
  when: not website_enabled.stat.exists
  changed_when: not website_enabled.stat.exists
- name: Check if SSL module is enabled
  ansible.builtin.stat:
    path: /etc/apache2/mods-enabled/ssl.load
  register: ssl_enabled
- name: Activate SSL on Apache
  ansible.builtin.command: a2enmod ssl
  notify:
    - Restart apache
  when: not ssl_enabled.stat.exists
  changed_when: not ssl_enabled.stat.exists
