---
controller_credentials:
- name: Chef Automate Deployment - poodle_fix
  description: Credentials used for Chef Automate and Chef Infra Server deployment
  organization: Default
  credential_type: Chef Automate Deployment
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
