---
controller_credential_types:
- name: Chef Admin User
  description: Credential type for Chef Admin User
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Chef admin username for initial user creation
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for the Chef admin user
    - id: full_name
      type: string
      label: Full Name
      help_text: Full name of the Chef admin user
    - id: email
      type: string
      label: Email
      help_text: Email address for the Chef admin user
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      full_name: !unsafe '{{ full_name }}'
      email: !unsafe '{{ email }}'
