---
controller_credential_types:
- name: Chef Server Deployment Credentials
  description: Credentials used in Chef server deployment scripts
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for Chef server administration
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef server administration
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
