---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Set vm.max_map_count
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: true
  become: true
- name: Set vm.dirty_expire_centisecs
  ansible.posix.sysctl:
    name: vm.dirty_expire_centisecs
    value: "20000"
    state: present
    reload: true
  become: true
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip
    dest: /tmp/chef-automate_linux_amd64.zip
    mode: "0644"
  become: true
- name: Unzip Chef Automate CLI
  ansible.builtin.unarchive:
    src: /tmp/chef-automate_linux_amd64.zip
    dest: /tmp/
    remote_src: true
  become: true
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: /tmp/chef-automate
    mode: "0755"
  become: true
- name: Check if Chef Automate is already deployed
  ansible.builtin.command:
    cmd: chef-automate status
  become: true
  register: automate_status
  changed_when: false
  failed_when: false
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: /tmp/chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa=true
  become: true
  register: deploy_result
  changed_when: deploy_result.rc == 0
  failed_when: deploy_result.rc != 0
  when: automate_status.rc != 0
- name: Check if Chef user already exists
  ansible.builtin.command:
    cmd: chef-server-ctl user-list
  become: true
  register: user_list
  changed_when: false
  failed_when: false
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create {{ chef_automate_username }} "{{ full_name }}" "{{ email }}" "{{ password }}" --filename {{ chef_automate_username }}.pem
  become: true
  register: user_create_result
  changed_when: user_create_result.rc == 0
  failed_when: user_create_result.rc != 0
  when: chef_automate_username not in user_list.stdout
- name: Check if Chef organization already exists
  ansible.builtin.command:
    cmd: chef-server-ctl org-list
  become: true
  register: org_list
  changed_when: false
  failed_when: false
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create {{ chef_automate_orgname }} "{{ chef_automate_longorgname }}" --association_user {{ chef_automate_username }} --filename {{
      chef_automate_orgname }}-validator.pem
  become: true
  register: org_create_result
  changed_when: org_create_result.rc == 0
  failed_when: org_create_result.rc != 0
  when: chef_automate_orgname not in org_list.stdout
