---
controller_credentials:
- name: Chef Automate User Credentials - chef_and_ansible
  description: User credentials for Chef Automate deployment
  organization: Default
  credential_type: Chef Automate User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Chef Infra Server Credentials - chef_and_ansible
  description: User credentials for Chef Infra Server deployment
  organization: Default
  credential_type: Chef Infra Server Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    organization: '{{ organization }}'
