- name: Converge
  hosts: all
  gather_facts: true
  tasks:
  - name: Create expected directories
    ansible.builtin.file:
      path: '{{ item }}'
      state: directory
      mode: '0755'
    loop:
    - /tmp/molecule_test/etc
    - /tmp/molecule_test/hab
    - /tmp/molecule_test/tmp/chef-automate
    - /tmp/molecule_test/usr/bin
  - name: Create hostname file
    ansible.builtin.copy:
      content: automate.chef.lab
      dest: /tmp/molecule_test/etc/hostname
      mode: '0644'
  - name: Create hosts file
    ansible.builtin.copy:
      content: '127.0.0.1 localhost

        127.0.0.1 automate.chef.lab

        '
      dest: /tmp/molecule_test/etc/hosts
      mode: '0644'
  - name: Create sysctl.conf file
    ansible.builtin.copy:
      content: 'vm.max_map_count=262144

        vm.dirty_expire_centisecs=20000

        '
      dest: /tmp/molecule_test/etc/sysctl.conf
      mode: '0644'
  - name: Create Chef Automate CLI file
    ansible.builtin.copy:
      content: '#!/bin/sh echo ''Chef Automate CLI mock'' '
      dest: /tmp/molecule_test/tmp/chef-automate/chef-automate
      mode: '0755'
  - name: Create Chef user key file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY-----

        MIIEpAIBAAKCAQEA1234567890abcdefghijklmnopqrstuvwxyz

        (mock key content)

        -----END RSA PRIVATE KEY-----

        '
      dest: /tmp/molecule_test/admin.pem
      mode: '0600'
  - name: Create Chef organization key file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY-----

        MIIEpAIBAAKCAQEA0987654321zyxwvutsrqponmlkjihgfedcba

        (mock key content)

        -----END RSA PRIVATE KEY-----

        '
      dest: /tmp/molecule_test/lab-validator.pem
      mode: '0600'
  - name: Create Chef Automate deployment marker
    ansible.builtin.file:
      path: /tmp/molecule_test/hab/sup
      state: directory
      mode: '0755'
  - name: Create chef-server-ctl mock
    ansible.builtin.copy:
      content: '#!/bin/sh

        echo "Chef Server Control mock"

        echo "Command: $@"

        exit 0

        '
      dest: /tmp/molecule_test/usr/bin/chef-server-ctl
      mode: '0755'
