---
automate_deploy_hostname: automate.chef.lab
automate_deploy_kernel_params:
  vm.max_map_count: 262144
  vm.dirty_expire_centisecs: 20000
automate_deploy_cli_url: https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip
automate_deploy_cli_path: /tmp/chef-automate
automate_deploy_user_pem_path: /tmp/{{ username }}.pem
automate_deploy_org_validator_pem_path: /tmp/{{ org_name }}-validator.pem
