---
controller_credentials:
- name: Chef Deployment Password - chef_automate_deployment
  description: Password used for Chef user creation during deployment
  organization: Default
  credential_type: Chef Deployment Password
  update_secrets: true
  inputs:
    user_password: '{{ vault_user_password }}'
