---
controller_credential_types:
- name: Chef Deployment User
  description: Credentials used in Chef deployment scripts for creating admin users
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for Chef Automate/Infra Server deployment
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef Automate/Infra Server user
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
