- name: Converge
  hosts: all
  gather_facts: true
  vars:
    username: jtonello
    chef_automate_org_name: lab
  tasks:
  - name: Create expected directories
    ansible.builtin.file:
      path: '{{ item }}'
      state: directory
      mode: '0755'
    loop:
    - /tmp/molecule_test/etc/chef-automate
    - /tmp/molecule_test/etc/chef-server
    - /tmp/molecule_test/etc/chef
    - /tmp/molecule_test/usr/bin
  - name: Create Chef Automate CLI file
    ansible.builtin.copy:
      content: '#!/bin/bash echo ''Chef Automate CLI Mock'' '
      dest: /tmp/molecule_test/usr/bin/chef-automate
      mode: '0755'
  - name: Create Chef Server CLI file
    ansible.builtin.copy:
      content: '#!/bin/bash echo ''Chef Server CLI Mock'' '
      dest: /tmp/molecule_test/usr/bin/chef-server-ctl
      mode: '0755'
  - name: Create Chef Automate config file
    ansible.builtin.copy:
      content: '# Chef Automate configuration

        [global]

        fqdn = "automate.chef.lab"

        '
      dest: /tmp/molecule_test/etc/chef-automate/config.toml
      mode: '0644'
  - name: Create Chef Server config file
    ansible.builtin.copy:
      content: '# Chef Server configuration

        nginx[''ssl_port''] = 443

        nginx[''server_name''] = "automate.chef.lab"

        '
      dest: /tmp/molecule_test/etc/chef-server/chef-server.rb
      mode: '0644'
  - name: Create user PEM file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY-----

        MIIEpAIBAAKCAQEAu7YuNtof6oV6E7tZxOOJx3EwQGgkGfON5ze+KZkn3qDm5K7q

        ...mock key content...

        -----END RSA PRIVATE KEY-----

        '
      dest: /tmp/molecule_test/{{ username }}.pem
      mode: '0600'
  - name: Create organization validator PEM file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY-----

        MIIEpAIBAAKCAQEAu7YuNtof6oV6E7tZxOOJx3EwQGgkGfON5ze+KZkn3qDm5K7q

        ...mock key content...

        -----END RSA PRIVATE KEY-----

        '
      dest: /tmp/molecule_test/{{ chef_automate_org_name }}-validator.pem
      mode: '0600'
  - name: Create hostname file
    ansible.builtin.copy:
      content: automate.chef.lab
      dest: /tmp/molecule_test/etc/hostname
      mode: '0644'
  - name: Create sysctl configuration
    ansible.builtin.copy:
      content: 'vm.max_map_count = 262144

        vm.dirty_expire_centisecs = 20000

        '
      dest: /tmp/molecule_test/etc/sysctl.d/99-chef-automate.conf
      mode: '0644'
