---
chef_automate_sysctl_params:
  vm.max_map_count: 262144
  vm.dirty_expire_centisecs: 20000
chef_automate_cli_path: "{{ ansible_env.HOME }}/chef-automate"
chef_automate_products:
  - automate
  - infra-server
