---
chef_automate_hostname: automate.chef.lab
chef_automate_vm_max_map_count: 262144
chef_automate_vm_dirty_expire_centisecs: 20000
chef_automate_cli_url: https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip
chef_automate_cli_path: /usr/local/bin/chef-automate
chef_automate_accept_terms: true
chef_automate_products:
  - automate
  - infra-server
chef_server_username: "{{ username | default('admin') }}"
chef_server_longusername: "{{ username | default('Administrator') }}"
chef_server_useremail: "{{ email | default('admin@example.com') }}"
chef_server_userpassword: "{{ password | default('password') }}"
chef_server_orgname: "{{ org_name | default('default') }}"
chef_server_longorgname: "{{ org_full_name | default('Default Organization') }}"
chef_server_userfilename: "{{ chef_server_username }}.pem"
chef_server_orgfilename: "{{ chef_server_orgname }}-validator.pem"
chef_server_pem_dir: /etc/chef
