---
controller_credentials:
- name: Chef Automate Deployment - poodle_fix
  description: Credential for poodle_fix
  organization: Default
  credential_type: Chef Automate Deployment
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Chef Infra Server Deployment - poodle_fix
  description: Credential for poodle_fix
  organization: Default
  credential_type: Chef Infra Server Deployment
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
