---
controller_credential_types:
- name: Chef Automate Setup Credentials
  description: Credential type for Chef Automate Setup Credentials
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for Chef Automate/Infra Server setup
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef Automate/Infra Server setup
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
- name: Chef Server Setup Credentials
  description: Credential type for Chef Server Setup Credentials
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for Chef Infra Server setup
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef Infra Server setup
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
