---
chef_automate_actual_username: "{{ username | default(chef_automate_username) }}"
chef_automate_actual_full_name: "{{ full_name | default(chef_automate_full_name) }}"
chef_automate_actual_email: "{{ email | default(chef_automate_email) }}"
chef_automate_actual_password: "{{ password | default(chef_automate_password) }}"
chef_automate_actual_org_name: "{{ org_short_name | default(chef_automate_org_name) }}"
chef_automate_actual_org_full_name: "{{ org_full_name | default(chef_automate_org_full_name) }}"
chef_automate_actual_user_key_file: "{{ user_key_file | default(chef_automate_user_key_file) }}"
chef_automate_actual_org_validator_key_file: "{{ org_validator_key_file | default(chef_automate_org_validator_key_file) }}"
