---
controller_credential_types:
- name: Chef Admin User
  description: Credential type for Chef Admin User
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Chef admin username
    - id: user_password
      type: string
      label: User Password
      secret: true
      help_text: Password for the Chef admin user
    - id: long_username
      type: string
      label: Full Name
      help_text: Full name of the admin user
    - id: user_email
      type: string
      label: Email Address
      help_text: Email address for the admin user
    - id: org_name
      type: string
      label: Organization Name
      help_text: Short name for the Chef organization
    - id: long_org_name
      type: string
      label: Organization Full Name
      help_text: Full name of the Chef organization
    required:
    - username
    - user_password
    - org_name
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      user_password: !unsafe '{{ user_password }}'
      long_username: !unsafe '{{ long_username }}'
      user_email: !unsafe '{{ user_email }}'
      org_name: !unsafe '{{ org_name }}'
      long_org_name: !unsafe '{{ long_org_name }}'
