---
controller_credential_types:
- name: Chef User Credentials
  description: Credential type for Chef User Credentials
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Chef user account username
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for the Chef user account
    - id: user_key
      type: string
      label: User PEM Key
      secret: true
      help_text: Authentication key file for the Chef user
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      user_key: !unsafe '{{ user_key }}'
- name: Chef Organization Credentials
  description: Credential type for Chef Organization Credentials
  kind: cloud
  inputs:
    fields:
    - id: org_name
      type: string
      label: Organization Name
      help_text: Short name for the Chef organization
    - id: org_validator_key
      type: string
      label: Organization Validator Key
      secret: true
      help_text: Authentication key for the Chef organization validator
    required:
    - org_name
    - org_validator_key
  injectors:
    extra_vars:
      org_name: !unsafe '{{ org_name }}'
      org_validator_key: !unsafe '{{ org_validator_key }}'
- name: Chef Automate Admin Credentials
  description: Credential type for Chef Automate Admin Credentials
  kind: cloud
  inputs:
    fields:
    - id: admin_username
      type: string
      label: Admin Username
      help_text: Username for Chef Automate web UI access
    - id: admin_password
      type: string
      label: Admin Password
      secret: true
      help_text: Password for Chef Automate web UI access
    required:
    - admin_username
    - admin_password
  injectors:
    extra_vars:
      admin_username: !unsafe '{{ admin_username }}'
      admin_password: !unsafe '{{ admin_password }}'
