---
- name: Create Chef admin user
  ansible.builtin.command:
    cmd: sudo chef-server-ctl user-create {{ username }} {{ first_name }} {{ last_name }} {{ email }} "{{ password }}" --filename {{ user_pem_filename }}
  args:
    creates: "{{ user_pem_filename }}"
  register: user_create_result
  changed_when: user_create_result.rc == 0
  failed_when: user_create_result.rc != 0
  become: true
  no_log: true
- name: Create Chef organization and associate admin user
  ansible.builtin.command:
    cmd: sudo chef-server-ctl org-create {{ chef_org_name }} "{{ chef_org_long_name }}" --association_user {{ username }} --filename {{
      org_validator_pem_filename }}
  args:
    creates: "{{ org_validator_pem_filename }}"
  register: org_create_result
  changed_when: org_create_result.rc == 0
  failed_when: org_create_result.rc != 0
  become: true
