---
# RedHat family specific variables
profile_redis_cluster_package_name: redis
profile_redis_cluster_service_name: redis
profile_redis_cluster_config_dir: /etc/redis
profile_redis_cluster_config_file: /etc/redis/redis.conf
profile_redis_cluster_log_dir: /var/log/redis
profile_redis_cluster_workdir: /var/lib/redis
profile_redis_cluster_bin_path: /usr/bin/redis-server
