---
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: /tmp/chef-automate.zip
    mode: "0644"
  register: download_result
- name: Check if Chef Automate CLI exists
  ansible.builtin.stat:
    path: /tmp/chef-automate
  register: automate_cli_stat
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip - > /tmp/chef-automate
    stdin: "{{ download_result.dest }}"
    creates: /tmp/chef-automate
  when: download_result.changed or not automate_cli_stat.stat.exists
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: /tmp/chef-automate
    mode: "0755"
    state: file
  when: download_result.changed or not automate_cli_stat.stat.exists
- name: Deploy Chef Automate with Infra Server
  ansible.builtin.command:
    cmd: "/tmp/chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa={{ 'true' if chef_automate_accept_terms else 'false' }} "
  become: true
  when: deploy_automate | bool
  register: automate_deploy
  changed_when: "'Chef Automate deployed' in automate_deploy.stdout"
  failed_when:
    - automate_deploy.rc != 0
    - "'already deployed' not in automate_deploy.stderr"
- name: Deploy Chef Infra Server only
  ansible.builtin.command:
    cmd: "/tmp/chef-automate deploy --product infra-server --accept-terms-and-mlsa={{ 'true' if chef_automate_accept_terms else 'false' }} "
  become: true
  when: not deploy_automate | bool
  register: server_deploy
  changed_when: "'Chef Infra Server deployed' in server_deploy.stdout"
  failed_when:
    - server_deploy.rc != 0
    - "'already deployed' not in server_deploy.stderr"
