---
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: /etc/apache2/mods-available/ssl.conf
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol {{ ssl_protocols }}
  notify:
    - Restart apache2
