---
- name: Gather service facts
  ansible.builtin.service_facts:
- name: Ensure Apache is installed
  ansible.builtin.package:
    name: apache2
    state: present
- name: Ensure OpenSSH server is installed
  ansible.builtin.package:
    name: openssh-server
    state: present
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: "{{ apache_ssl_conf_path }}"
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol {{ ssl_protocol_setting }}
    mode: "0644"
  notify:
    - Restart apache2
    - Restart sshd
