---
- name: Ensure key file directories exist
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "{{ chef_automate_user_key_path }}"
    - "{{ chef_automate_org_key_path }}"
  become: true
  when: ansible_user is defined
- name: Create Chef user
  ansible.builtin.command:
    cmd: 'chef-server-ctl user-create {{ chef_automate_username }} {{ chef_automate_full_name }} {{ chef_automate_email }} "{{ chef_automate_password }}" --filename
      {{ chef_automate_user_key_path }}

      '
  args:
    creates: "{{ chef_automate_user_key_path }}"
  become: true
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: 'chef-server-ctl org-create {{ chef_automate_org_name }} "{{ chef_automate_org_full_name }}" --association_user {{ chef_automate_username }} --filename {{
      chef_automate_org_key_path }}

      '
  args:
    creates: "{{ chef_automate_org_key_path }}"
  become: true
- name: Set proper ownership of key files
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  loop:
    - "{{ chef_automate_user_key_path }}"
    - "{{ chef_automate_org_key_path }}"
  become: true
  when: ansible_user is defined
