---
controller_credentials:
- name: Chef Server User Credentials - chef_automate_deployment
  description: Credentials used for creating and managing Chef Server users
  organization: Default
  credential_type: Chef Server User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    email: '{{ email }}'
- name: Chef Organization Validator - chef_automate_deployment
  description: Credentials used for Chef Server organization creation and validation
  organization: Default
  credential_type: Chef Organization Validator
  update_secrets: true
  inputs:
    organization_name: '{{ organization_name }}'
    full_organization_name: '{{ full_organization_name }}'
    validator_key: '{{ vault_validator_key }}'
