---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  become: true
- name: Set vm.max_map_count kernel parameter
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_map_count }}"
    state: present
    sysctl_set: true
  become: true
- name: Set vm.dirty_expire_centisecs kernel parameter
  ansible.posix.sysctl:
    name: vm.dirty_expire_centisecs
    value: "{{ vm_dirty_expire_centisecs }}"
    state: present
    sysctl_set: true
  become: true
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: /tmp/chef-automate.zip
    mode: "0644"
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip -c /tmp/chef-automate.zip > /tmp/chef-automate
  args:
    creates: /tmp/chef-automate
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: /tmp/chef-automate
    mode: "0755"
    state: file
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: /tmp/chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa=true
  args:
    creates: /hab
  become: true
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create {{ username }} {{ longusername }} {{ useremail }} "{{ userpassword }}" --filename {{ userfilename }}
  args:
    creates: "{{ userfilename }}"
  become: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create {{ orgname }} "{{ longorgname }}" --association_user {{ username }} --filename {{ orgfilename }}
  args:
    creates: "{{ orgfilename }}"
  become: true
