---
- name: Ensure Apache is installed
  ansible.builtin.package:
    name: apache2
    state: present
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: "{{ apache_ssl_conf_path }}"
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol {{ poodle_fix_ssl_protocol }}
  notify:
    - Restart apache
    - Restart sshd
