---
- name: Validate required credential variables are defined
  ansible.builtin.assert:
    that:
      - username is defined
      - password is defined
      - username is defined
      - pem_content is defined
      - organization_name is defined
      - validator_pem_content is defined
    fail_msg: One or more required credential variables are not defined. Ensure the AAP credential type is attached to the job template.
    quiet: true
