---
apache_version: 2.4.41-4ubuntu3.10
ssl_cert_path: /etc/apache2/certs
ssl_key_file: "{{ ssl_cert_path }}/apache.key"
ssl_csr_file: "{{ ssl_cert_path }}/apache.csr"
ssl_cert_file: "{{ ssl_cert_path }}/apache.crt"
site_name: helloworld
document_root: /var/www/helloworld
server_name: myhost
ssl_protocol: -all +TLSv1.2
