- name: Converge
  hosts: all
  vars:
    conftext: "<VirtualHost *:443>\n DocumentRoot \"/var/www/helloworld\"\n SSLEngine on\n SSLCertificateFile /etc/apache2/certs/apache.crt\n SSLCertificateKeyFile
      /etc/apache2/certs/apache.key\n  <Directory \"/var/www/helloworld\">\n    allow from all\n    Options None\n    Require all granted\n  </Directory>\n</VirtualHost>\n"
    webtext: "<html>\n  <head><title>Test Site</title>/head>\n  <body>\n   <h1>Hello, world!</h1>\n   <p>The site is up and running</p>\n  </body>\n</html>\n"
  tasks:
  - name: Include chef_and_ansible role
    ansible.builtin.include_role:
      name: chef_and_ansible
      tasks_from: website_https
