- name: Converge
  hosts: all
  gather_facts: true
  tasks:
  - name: Create expected directories
    ansible.builtin.file:
      path: '{{ item }}'
      state: directory
      mode: '0755'
    loop:
    - /tmp/molecule_test/etc
    - /tmp/molecule_test/proc/sys/vm
    - /tmp/molecule_test/hab
    - /tmp/molecule_test/tmp
  - name: Create hostname file
    ansible.builtin.copy:
      content: automate.chef.lab
      dest: /tmp/molecule_test/etc/hostname
      mode: '0644'
  - name: Create max_map_count file
    ansible.builtin.copy:
      content: '262144'
      dest: /tmp/molecule_test/proc/sys/vm/max_map_count
      mode: '0644'
  - name: Create dirty_expire_centisecs file
    ansible.builtin.copy:
      content: '20000'
      dest: /tmp/molecule_test/proc/sys/vm/dirty_expire_centisecs
      mode: '0644'
  - name: Create chef-automate CLI file
    ansible.builtin.copy:
      content: '#!/bin/bash echo ''Chef Automate CLI'''
      dest: /tmp/molecule_test/tmp/chef-automate
      mode: '0755'
  - name: Create hab directory to simulate successful deployment
    ansible.builtin.file:
      path: /tmp/molecule_test/hab
      state: directory
      mode: '0755'
  - name: Create user PEM file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY----- MIIEpAIBAAKCAQEA... -----END RSA PRIVATE KEY----- '
      dest: /tmp/molecule_test/jtonello.pem
      mode: '0600'
  - name: Create organization validator PEM file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY----- MIIEpAIBAAKCAQEA... -----END RSA PRIVATE KEY----- '
      dest: /tmp/molecule_test/lab-validator.pem
      mode: '0600'
  - name: Create chef-automate status file
    ansible.builtin.copy:
      content: 'Service: chef-automate Status: running'
      dest: /tmp/molecule_test/chef-automate-status
      mode: '0644'
  - name: Create chef-server-ctl status file
    ansible.builtin.copy:
      content: 'Service: chef-server Status: running'
      dest: /tmp/molecule_test/chef-server-status
      mode: '0644'
  - name: Create user list file
    ansible.builtin.copy:
      content: jtonello
      dest: /tmp/molecule_test/chef-user-list
      mode: '0644'
  - name: Create organization list file
    ansible.builtin.copy:
      content: lab
      dest: /tmp/molecule_test/chef-org-list
      mode: '0644'
  - name: Create systemd service status files
    ansible.builtin.copy:
      content: '● chef-automate.service - Chef Automate Loaded: loaded Active: active (running)'
      dest: /tmp/molecule_test/chef-automate-service
      mode: '0644'
