- name: Converge
  hosts: all
  gather_facts: true
  vars:
    username: test_user
    full_name: Test User
    email: test@example.com
    password: test_password
    pem_file: /tmp/test_user.pem
    org_name: test_org
    org_full_name: Test Organization
    validator_pem: /tmp/test_org-validator.pem
    chef_automate_hostname: automate.chef.lab
    chef_automate_cli_path: /tmp/chef-automate
    chef_automate_user_pem_path: /tmp/test_user.pem
    chef_automate_org_pem_path: /tmp/test_org-validator.pem
  tasks:
  - name: Create expected directories
    ansible.builtin.file:
      path: '{{ item }}'
      state: directory
      mode: '0755'
    loop:
    - /tmp/molecule_test/hab
    - /tmp/molecule_test/tmp
    - /tmp/molecule_test/etc/sysctl.d
  - name: Create Chef Automate CLI file
    ansible.builtin.copy:
      content: '#!/bin/bash echo ''Chef Automate CLI Mock'' '
      dest: /tmp/molecule_test/tmp/chef-automate
      mode: '0755'
  - name: Create user PEM file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY----- MOCK USER PEM CONTENT -----END RSA PRIVATE KEY----- '
      dest: /tmp/molecule_test/tmp/test_user.pem
      mode: '0600'
  - name: Create organization validator PEM file
    ansible.builtin.copy:
      content: '-----BEGIN RSA PRIVATE KEY----- MOCK ORG VALIDATOR PEM CONTENT -----END RSA PRIVATE KEY----- '
      dest: /tmp/molecule_test/tmp/test_org-validator.pem
      mode: '0600'
  - name: Create sysctl configuration files
    ansible.builtin.copy:
      content: '{{ item.name }} = {{ item.value }} '
      dest: /tmp/molecule_test/etc/sysctl.d/{{ item.name | replace('.', '-') }}.conf
      mode: '0644'
    loop:
    - name: vm.max_map_count
      value: '262144'
    - name: vm.dirty_expire_centisecs
      value: '20000'
