---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Configure vm.max_map_count
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ chef_automate_vm_max_map_count }}"
    state: present
    reload: true
  become: true
  notify: Apply sysctl settings
- name: Configure vm.dirty_expire_centisecs
  ansible.posix.sysctl:
    name: vm.dirty_expire_centisecs
    value: "{{ chef_automate_vm_dirty_expire_centisecs }}"
    state: present
    reload: true
  become: true
  notify: Apply sysctl settings
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: /tmp/chef-automate_linux_amd64.zip
    mode: "0644"
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip < /tmp/chef-automate_linux_amd64.zip > {{ chef_automate_cli_binary }} && chmod +x {{ chef_automate_cli_binary }}
    chdir: "{{ ansible_env.PWD }}"
    creates: "{{ ansible_env.PWD }}/{{ chef_automate_cli_binary }}"
- name: Check if Chef Automate is already deployed
  ansible.builtin.stat:
    path: /var/opt/chef-automate
  register: chef_automate_dir
  become: true
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: ./{{ chef_automate_cli_binary }} deploy --product automate --product infra-server --accept-terms-and-mlsa=true
    chdir: "{{ ansible_env.PWD }}"
  become: true
  register: deploy_result
  changed_when: deploy_result.rc == 0
  failed_when: deploy_result.rc != 0
  when: not chef_automate_dir.stat.exists
- name: Check if Chef user already exists
  ansible.builtin.stat:
    path: "{{ ansible_env.PWD }}/{{ chef_automate_userfilename }}"
  register: chef_user_file
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create {{ chef_automate_username }} {{ chef_automate_longusername }} {{ chef_automate_useremail }} "{{ password }}" --filename {{
      chef_automate_userfilename }}
    chdir: "{{ ansible_env.PWD }}"
  become: true
  no_log: true
  when: not chef_user_file.stat.exists
- name: Check if Chef organization already exists
  ansible.builtin.stat:
    path: "{{ ansible_env.PWD }}/{{ chef_automate_orgfilename }}"
  register: chef_org_file
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create {{ chef_automate_orgname }} "{{ chef_automate_longorgname }}" --association_user {{ chef_automate_username }} --filename {{
      chef_automate_orgfilename }}
    chdir: "{{ ansible_env.PWD }}"
  become: true
  when: not chef_org_file.stat.exists
