---
controller_credential_types:
- name: Chef User Credentials
  description: Credential type for Chef User Credentials
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Chef user account username
    - id: long_username
      type: string
      label: Full Name
      help_text: Chef user's full name
    - id: user_email
      type: string
      label: Email Address
      help_text: Chef user's email address
    - id: user_password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef user account
    required:
    - username
    - user_password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      long_username: !unsafe '{{ long_username }}'
      user_email: !unsafe '{{ user_email }}'
      user_password: !unsafe '{{ user_password }}'
- name: Chef Organization Credentials
  description: Credential type for Chef Organization Credentials
  kind: cloud
  inputs:
    fields:
    - id: org_name
      type: string
      label: Organization Name
      help_text: Short name for Chef organization
    - id: long_org_name
      type: string
      label: Organization Full Name
      help_text: Full descriptive name for Chef organization
    required:
    - org_name
  injectors:
    extra_vars:
      org_name: !unsafe '{{ org_name }}'
      long_org_name: !unsafe '{{ long_org_name }}'
