- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check if Apache SSL config file exists
    ansible.builtin.stat:
      path: /tmp/molecule_test/etc/apache2/mods-available/ssl.conf
    register: ssl_conf_file
  - name: Assert SSL config file exists
    ansible.builtin.assert:
      that:
      - ssl_conf_file.stat.exists
      - ssl_conf_file.stat.isreg
      fail_msg: Apache SSL config file not found
      success_msg: Apache SSL config file exists
  - name: Get SSL config file content
    ansible.builtin.slurp:
      src: /tmp/molecule_test/etc/apache2/mods-available/ssl.conf
    register: ssl_conf_content
  - name: Assert SSL config has been properly updated for POODLE mitigation
    ansible.builtin.assert:
      that:
      - '''SSLProtocol -all +TLSv1.2'' in ssl_conf_content.content | b64decode'
      - '''SSLProtocol all -SSLv3'' not in ssl_conf_content.content | b64decode'
      fail_msg: SSL configuration was not properly updated to mitigate POODLE vulnerability
      success_msg: SSL configuration was properly updated to mitigate POODLE vulnerability
  - name: Check Apache service status
    ansible.builtin.service_facts: null
    tags: molecule-notest
  - name: Assert Apache service is running
    ansible.builtin.assert:
      that:
      - '''apache2.service'' in ansible_facts.services'
      - ansible_facts.services['apache2.service'].state == 'running'
      fail_msg: Apache service is not running
      success_msg: Apache service is running
    tags: molecule-notest
  - name: Validate Apache configuration
    ansible.builtin.command: apache2ctl configtest
    changed_when: false
    tags: molecule-notest
