---
deploy_automate: true
deploy_infra_server: true
accept_terms_and_mlsa: true
configure_hostname: true
configure_sysctl: true
chef_automate_cli_download_path: /tmp
chef_automate_cli_path: /tmp/chef-automate
key_file_storage_path: .
