---
controller_credential_types:
- name: Chef Admin User Credentials
  description: Credential type for Chef Admin User Credentials
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Admin Username
      help_text: Username for the initial Chef admin user
    - id: password
      type: string
      label: Admin Password
      secret: true
      help_text: Password for the initial Chef admin user
    - id: full_name
      type: string
      label: Full Name
      help_text: Full name of the Chef admin user
    - id: email
      type: string
      label: Email Address
      help_text: Email address of the Chef admin user
    required:
    - username
    - password
    - full_name
    - email
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
      full_name: !unsafe '{{ full_name }}'
      email: !unsafe '{{ email }}'
- name: Chef Organization Configuration
  description: Credential type for Chef Organization Configuration
  kind: cloud
  inputs:
    fields:
    - id: org_name
      type: string
      label: Organization Name
      help_text: Short name for the Chef organization
    - id: org_full_name
      type: string
      label: Organization Full Name
      help_text: Full descriptive name for the Chef organization
    required:
    - org_name
    - org_full_name
  injectors:
    extra_vars:
      org_name: !unsafe '{{ org_name }}'
      org_full_name: !unsafe '{{ org_full_name }}'
- name: Chef User PEM
  description: Credential type for Chef User PEM
  kind: cloud
  inputs:
    fields:
    - id: user_pem
      type: string
      label: User PEM File
      secret: true
      help_text: Authentication key for the Chef admin user
    required:
    - user_pem
  injectors:
    extra_vars:
      user_pem: !unsafe '{{ user_pem }}'
- name: Chef Organization Validator PEM
  description: Credential type for Chef Organization Validator PEM
  kind: cloud
  inputs:
    fields:
    - id: org_validator_pem
      type: string
      label: Organization Validator PEM File
      secret: true
      help_text: Authentication key for the Chef organization validator
    required:
    - org_validator_pem
  injectors:
    extra_vars:
      org_validator_pem: !unsafe '{{ org_validator_pem }}'
