---
- name: Create Chef user
  ansible.builtin.command:
    cmd: 'chef-server-ctl user-create  {{ chef_user_name }}  {{ chef_user_fullname }}  {{ chef_user_email }}  "{{ user_password }}"  --filename {{ chef_user_key_file
      }}

      '
  args:
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/{{ chef_user_key_file }}"
  become: true
  no_log: true
  register: chef_user_create
  changed_when: chef_user_create.rc == 0
- name: Create Chef organization
  ansible.builtin.command:
    cmd: 'chef-server-ctl org-create  {{ chef_org_name }}  "{{ chef_org_fullname }}"  --association_user {{ chef_user_name }}  --filename {{ chef_org_validator_key_file
      }}

      '
  args:
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/{{ chef_org_validator_key_file }}"
  become: true
  register: chef_org_create
  changed_when: chef_org_create.rc == 0
