- name: Set system hostname
  ansible.builtin.hostname:
    name: '{{ chef_automate_hostname }}'
  become: true
- name: Set vm.max_map_count kernel parameter
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '{{ chef_automate_vm_max_map_count }}'
    state: present
    reload: true
    sysctl_set: true
  become: true
- name: Set vm.dirty_expire_centisecs kernel parameter
  ansible.posix.sysctl:
    name: vm.dirty_expire_centisecs
    value: '{{ chef_automate_vm_dirty_expire_centisecs }}'
    state: present
    reload: true
    sysctl_set: true
  become: true
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: '{{ chef_automate_cli_url }}'
    dest: /tmp/chef-automate.zip
    mode: '0644'
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip - > chef-automate
    stdin: '{{ lookup(''file'', ''/tmp/chef-automate.zip'') }}'
    chdir: /tmp
    creates: /tmp/chef-automate
  args:
    executable: /bin/bash
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: /tmp/chef-automate
    mode: '0755'
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: ./chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa={{ chef_automate_accept_terms | lower }}
    chdir: /tmp
    creates: /etc/chef-automate/config.toml
  become: true
- name: Create Chef user
  ansible.builtin.command:
    cmd: 'chef-server-ctl user-create  {{ chef_automate_username }}  {{ chef_automate_longusername }}  {{ chef_automate_useremail }}  "{{ password }}"  --filename
      {{ chef_automate_userfilename }}

      '
    creates: /home/{{ ansible_user }}/{{ chef_automate_userfilename }}
  become: true
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: 'chef-server-ctl org-create  {{ chef_automate_orgname }}  "{{ chef_automate_longorgname }}"  --association_user {{ chef_automate_username }}  --filename
      {{ chef_automate_orgfilename }}

      '
    creates: /home/{{ ansible_user }}/{{ chef_automate_orgfilename }}
  become: true
