---
deploy_automate: true
deploy_chef_server: false
chef_automate_hostname: automate.chef.lab
chef_username: admin
chef_longusername: Chef Admin
chef_useremail: admin@example.com
chef_userpassword: Ch4ng3M3!
chef_orgname: default
chef_longorgname: Default Organization
