---
controller_credentials:
- name: Chef Infra Server User - chef_automate_deployment
  description: Credential for chef_automate_deployment
  organization: Default
  credential_type: Chef Infra Server User
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    full_name: '{{ full_name }}'
    email: '{{ email }}'
