---
controller_credentials:
- name: Chef Admin User Credentials - chef_automate_deployment
  description: Credential for chef_automate_deployment
  organization: Default
  credential_type: Chef Admin User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    email: '{{ email }}'
    full_name: '{{ full_name }}'
