---
controller_credential_types:
- name: Chef User Password
  description: Credential type for Chef User Password
  kind: cloud
  inputs:
    fields:
    - id: user_password
      type: string
      label: User Password
      secret: true
      help_text: Password for the initial Chef user account for authentication to
        Chef Infra Server and Chef Automate
    - id: username
      type: string
      label: Username
      help_text: 'Username for the Chef user account (default: jtonello)'
    - id: full_name
      type: string
      label: Full Name
      help_text: 'Full name for the Chef user account (default: John Tonello)'
    - id: email
      type: string
      label: Email
      help_text: 'Email address for the Chef user account (default: jtonello@chef.lab)'
    required:
    - user_password
    - username
  injectors:
    extra_vars:
      user_password: !unsafe '{{ user_password }}'
      username: !unsafe '{{ username }}'
      full_name: !unsafe '{{ full_name }}'
      email: !unsafe '{{ email }}'
