---
controller_credential_types:
- name: Chef User Password
  description: Credential type for Chef User Password
  kind: cloud
  inputs:
    fields:
    - id: user_password
      type: string
      label: User Password
      secret: true
      help_text: Password for the initial Chef user account
    required:
    - user_password
  injectors:
    extra_vars:
      user_password: !unsafe '{{ user_password }}'
- name: Chef User Key
  description: Credential type for Chef User Key
  kind: cloud
  inputs:
    fields:
    - id: user_key
      type: string
      label: User Key
      secret: true
      help_text: Authentication key for the Chef user, stored as a .pem file
    required:
    - user_key
  injectors:
    extra_vars:
      user_key: !unsafe '{{ user_key }}'
- name: Chef Organization Validator Key
  description: Credential type for Chef Organization Validator Key
  kind: cloud
  inputs:
    fields:
    - id: org_validator_key
      type: string
      label: Organization Validator Key
      secret: true
      help_text: Authentication key for the Chef organization, stored as a .pem file
    required:
    - org_validator_key
  injectors:
    extra_vars:
      org_validator_key: !unsafe '{{ org_validator_key }}'
- name: Chef User Information
  description: Credential type for Chef User Information
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for the Chef user account
    - id: full_name
      type: string
      label: Full Name
      help_text: Full name for the Chef user account
    - id: email
      type: string
      label: Email Address
      help_text: Email address for the Chef user account
    - id: org_name
      type: string
      label: Organization Name
      help_text: Short name for the Chef organization
    - id: org_full_name
      type: string
      label: Organization Full Name
      help_text: Full name for the Chef organization
    required:
    - username
    - email
    - org_name
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      full_name: !unsafe '{{ full_name }}'
      email: !unsafe '{{ email }}'
      org_name: !unsafe '{{ org_name }}'
      org_full_name: !unsafe '{{ org_full_name }}'
