---
chef_server_hostname: automate.chef.lab
chef_server_username: jtonello
chef_server_longusername: John Tonello
chef_server_useremail: jtonello@chef.lab
chef_server_userpassword: password
chef_server_orgname: lab
chef_server_longorgname: Chef Lab
chef_server_userfilename: "{{ chef_server_username }}.pem"
chef_server_orgfilename: "{{ chef_server_orgname }}-validator.pem"
