---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
- name: Install necessary packages
  ansible.builtin.apt:
    name: apache2=2.4.41-4ubuntu3.10
- name: Install curl, openssl, PyOpenSSL
  ansible.builtin.apt:
    pkg:
      - curl
      - openssl
      - python3-openssl
