---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: configure_hostname | bool
  become: true
- name: Configure kernel parameter vm.max_map_count
  ansible.builtin.sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_map_count }}"
    state: present
    reload: true
  become: true
  when: configure_sysctl | bool
- name: Configure kernel parameter vm.dirty_expire_centisecs
  ansible.builtin.sysctl:
    name: vm.dirty_expire_centisecs
    value: "{{ vm_dirty_expire_centisecs }}"
    state: present
    reload: true
  become: true
  when: configure_sysctl | bool
