deploy_automate: true
accept_terms_and_mlsa: true
chef_automate_binary_path: '{{ ansible_env.HOME }}/chef-automate'
user_key_filename: '{{ ansible_env.HOME }}/{{ username }}.pem'
org_validator_filename: '{{ ansible_env.HOME }}/{{ orgname }}-validator.pem'
