---
controller_credentials:
- name: Chef Server User Credentials - deploy_automate
  description: Credential for deploy_automate
  organization: Default
  credential_type: Chef Server User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    long_username: '{{ long_username }}'
    user_email: '{{ user_email }}'
    user_password: '{{ vault_user_password }}'
- name: Chef Organization Credentials - deploy_automate
  description: Credential for deploy_automate
  organization: Default
  credential_type: Chef Organization Credentials
  update_secrets: true
  inputs:
    org_name: '{{ org_name }}'
    long_org_name: '{{ long_org_name }}'
