---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Configure system for Chef Automate
  ansible.builtin.include_tasks: system_config.yml
- name: Install Chef Automate with Infra Server
  ansible.builtin.include_tasks: install_automate.yml
  when: "'automate' in chef_automate_products"
- name: Install Chef Infra Server only
  ansible.builtin.include_tasks: install_chef_server.yml
  when: "'automate' not in chef_automate_products"
- name: Setup Chef users and organizations
  ansible.builtin.include_tasks: setup_users_orgs.yml
