---
hostname: automate.chef.lab
username: jtonello
full_name: John Tonello
email: jtonello@chef.lab
password: password
org_name: lab
org_full_name: Chef Lab
vm_max_map_count: 262144
vm_dirty_expire_centisecs: 20000
chef_automate_cli_url: https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip
chef_automate_cli_path: "{{ ansible_env.HOME }}/chef-automate"
deploy_automate: true
accept_terms_and_mlsa: true
user_key_filename: "{{ username }}.pem"
org_validator_key_filename: "{{ org_name }}-validator.pem"
validator_key: ""
