---
- name: Ensure Apache is installed
  ansible.builtin.package:
    name: "{{ apache_service_name }}"
    state: present
  become: true
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: "{{ apache_ssl_conf_path }}"
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol {{ apache_ssl_protocol }}
  notify:
    - Restart apache
    - Restart sshd
  become: true
