---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Include website HTTPS setup tasks
  ansible.builtin.include_tasks: website_https.yml
- name: Include SSL Poodle fix tasks
  ansible.builtin.include_tasks: poodle_fix.yml
