---
chef_automate_hostname: automate.chef.lab
chef_automate_username: jtonello
chef_automate_longusername: John Tonello
chef_automate_useremail: jtonello@chef.lab
chef_automate_orgname: lab
chef_automate_longorgname: Chef Lab
chef_automate_vm_max_map_count: 262144
chef_automate_vm_dirty_expire_centisecs: 20000
chef_automate_cli_url: https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip
chef_automate_deploy_automate: true
chef_automate_deploy_infra_server: true
chef_automate_accept_terms_and_mlsa: true
chef_automate_cli_path: ./chef-automate
