---
controller_credentials:
- name: Chef Deployment Credentials - poodle_fix
  description: Credentials used in Chef Automate and Chef Infra Server deployment
    scripts
  organization: Default
  credential_type: Chef Deployment Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
