---
chef_automate_username: "{{ username | default(chef_automate_username) }}"
chef_automate_user_fullname: "{{ full_name | default(chef_automate_user_fullname) }}"
chef_automate_user_email: "{{ email | default(chef_automate_user_email) }}"
chef_automate_user_password: "{{ password | default('password') }}"
chef_automate_user_key_path: "{{ chef_automate_username }}.pem"
chef_automate_org_key_path: "{{ chef_automate_org_name }}-validator.pem"
