---
- name: Validate required credential variables are defined
  ansible.builtin.assert:
    that:
      - username is defined or chef_automate_username is defined
      - password is defined or chef_automate_password is defined
      - full_name is defined or chef_automate_full_name is defined
      - email is defined or chef_automate_email is defined
    fail_msg: One or more required credential variables are not defined. Ensure the AAP credential type is attached to the job template.
    quiet: true
