---
controller_credentials:
- name: Chef Automate User Credentials - chef_and_ansible
  description: User credentials for Chef Automate deployment
  organization: Default
  credential_type: Chef Automate User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: SSL Certificate - chef_and_ansible
  description: SSL certificate for HTTPS website
  organization: Default
  credential_type: SSL Certificate
  update_secrets: true
  inputs:
    ssl_key: '{{ vault_ssl_key }}'
    ssl_certificate: '{{ ssl_certificate }}'
    ssl_csr: '{{ ssl_csr }}'
