- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check if ssl.conf exists
    ansible.builtin.stat:
      path: /tmp/molecule_test/etc/apache2/mods-available/ssl.conf
    register: ssl_conf_file
  - name: Assert ssl.conf file exists
    ansible.builtin.assert:
      that:
      - ssl_conf_file.stat.exists
      - ssl_conf_file.stat.isreg
      fail_msg: ssl.conf file does not exist
      success_msg: ssl.conf file exists
  - name: Get ssl.conf content
    ansible.builtin.slurp:
      src: /tmp/molecule_test/etc/apache2/mods-available/ssl.conf
    register: ssl_conf_content
    when: ssl_conf_file.stat.exists
  - name: Assert SSLProtocol is properly configured
    ansible.builtin.assert:
      that:
      - '''SSLProtocol -all +TLSv1.2'' in (ssl_conf_content.content | b64decode)'
      - '''SSLProtocol all -SSLv3'' not in (ssl_conf_content.content | b64decode)'
      fail_msg: SSLProtocol is not properly configured to mitigate POODLE vulnerability
      success_msg: SSLProtocol is properly configured to mitigate POODLE vulnerability
    when: ssl_conf_file.stat.exists
  - name: Check Apache configuration
    ansible.builtin.command: apache2ctl configtest
    changed_when: false
    tags: molecule-notest
  - name: Check SSL/TLS configuration
    ansible.builtin.command: nmap --script ssl-enum-ciphers -p 443 localhost
    changed_when: false
    tags: molecule-notest
  - name: Test SSL vulnerability
    ansible.builtin.command: openssl s_client -connect localhost:443 -ssl3
    register: ssl_test
    failed_when: ssl_test.rc == 0
    changed_when: false
    tags: molecule-notest
  - name: Check Apache service status
    ansible.builtin.service_facts: null
    tags: molecule-notest
  - name: Assert Apache service is running
    ansible.builtin.assert:
      that:
      - '''apache2.service'' in ansible_facts.services'
      - ansible_facts.services['apache2.service'].state == 'running'
      fail_msg: Apache service is not running
      success_msg: Apache service is running
    tags: molecule-notest
