---
- name: Set user variables
  ansible.builtin.set_fact:
    chef_user_name: "{{ username | default(chef_automate_username) }}"
    chef_user_full_name: "{{ full_name | default(chef_automate_full_name) }}"
    chef_user_email: "{{ email | default(chef_automate_email) }}"
    chef_user_password: "{{ password | default(chef_automate_password) }}"
    chef_user_key_path: "{{ user_key_path | default(chef_automate_user_key_path) }}"
    chef_org_short_name: "{{ org_short_name | default(chef_automate_org_short_name) }}"
    chef_org_full_name: "{{ org_full_name | default(chef_automate_org_full_name) }}"
    chef_org_validator_path: "{{ org_validator_path | default(chef_automate_org_validator_path) }}"
- name: Check if user key file exists
  ansible.builtin.stat:
    path: "{{ chef_user_key_path }}"
  register: user_key_file
  become: true
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create {{ chef_user_name }} {{ chef_user_full_name }} {{ chef_user_email }} "{{ chef_user_password }}" --filename {{
      chef_user_key_path }}
    creates: "{{ chef_user_key_path }}"
  become: true
  register: create_user
  changed_when: create_user.rc == 0
  no_log: true
  when: not user_key_file.stat.exists
- name: Check if organization validator key file exists
  ansible.builtin.stat:
    path: "{{ chef_org_validator_path }}"
  register: org_validator_file
  become: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create {{ chef_org_short_name }} "{{ chef_org_full_name }}" --association_user {{ chef_user_name }} --filename {{
      chef_org_validator_path }}
    creates: "{{ chef_org_validator_path }}"
  become: true
  register: create_org
  changed_when: create_org.rc == 0
  when: not org_validator_file.stat.exists
- name: Store user key content if provided
  ansible.builtin.copy:
    content: "{{ user_key_content | default('') }}"
    dest: "{{ chef_user_key_path }}"
    mode: "0600"
  become: true
  when: user_key_content is defined and user_key_content | length > 0
  no_log: true
- name: Store organization validator key content if provided
  ansible.builtin.copy:
    content: "{{ org_validator_content | default('') }}"
    dest: "{{ chef_org_validator_path }}"
    mode: "0600"
  become: true
  when: org_validator_content is defined and org_validator_content | length > 0
  no_log: true
