---
- name: Ensure Apache is installed
  ansible.builtin.package:
    name: apache2
    state: present
- name: Ensure SSH server is installed
  ansible.builtin.package:
    name: "{{ 'openssh-server' if ansible_os_family == 'Debian' else 'openssh-server' }}"
    state: present
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: "{{ apache_ssl_config_path }}"
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol {{ ssl_protocol_setting }}
  notify:
    - Restart Apache
    - Restart SSH
