---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Configure kernel parameters for Chef Automate/Chef Server
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ chef_automate_kernel_params | dict2items }}"
  become: true
