---
- name: Create Redis group
  ansible.builtin.group:
    name: redis
    system: true
    state: present
- name: Create Redis user
  ansible.builtin.user:
    name: redis
    group: redis
    system: true
    shell: /bin/false
    home: /var/lib/redis
    create_home: false
    state: present
- name: Add Redis repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: ppa:redislabs/redis
    state: present
    update_cache: true
  when:
    - redis_manage_repo | default(true)
    - ansible_os_family == "Debian"
- name: Add Redis repository (RHEL/CentOS)
  ansible.builtin.yum_repository:
    name: redis
    description: Redis repository
    baseurl: https://packages.redis.io/rpm/rhel{{ ansible_distribution_major_version }}/x86_64/
    gpgcheck: true
    gpgkey: https://packages.redis.io/gpg
    enabled: true
  when:
    - redis_manage_repo | default(true)
    - ansible_os_family == "RedHat"
