---
controller_credentials:
- name: Chef Admin User Credentials - chef_automate_deployment
  description: Credential for chef_automate_deployment
  organization: Default
  credential_type: Chef Admin User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    full_name: '{{ full_name }}'
    email: '{{ email }}'
- name: Chef Organization Configuration - chef_automate_deployment
  description: Credential for chef_automate_deployment
  organization: Default
  credential_type: Chef Organization Configuration
  update_secrets: true
  inputs:
    org_name: '{{ org_name }}'
    org_full_name: '{{ org_full_name }}'
- name: Chef Authentication Keys - chef_automate_deployment
  description: Credential for chef_automate_deployment
  organization: Default
  credential_type: Chef Authentication Keys
  update_secrets: true
  inputs:
    user_key: '{{ vault_user_key }}'
    org_validator_key: '{{ vault_org_validator_key }}'
