---
- name: Include system configuration tasks
  ansible.builtin.include_tasks:
    file: system_config.yml
- name: Ensure Chef Automate config directory exists
  ansible.builtin.file:
    path: /etc/chef-automate
    state: directory
    mode: "0755"
  become: true
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: sudo ./chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa={{ chef_automate_accept_terms_and_mlsa | lower }}
  args:
    creates: /etc/chef-automate/config.toml
  register: chef_automate_deploy
  changed_when: chef_automate_deploy.rc == 0
- name: Include tasks to create users and organizations
  ansible.builtin.include_tasks:
    file: create_users_orgs.yml
