---
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: /tmp/chef-automate.zip
    mode: "0644"
- name: Ensure unzip is installed
  ansible.builtin.package:
    name: unzip
    state: present
  become: true
- name: Extract Chef Automate CLI
  ansible.builtin.unarchive:
    src: /tmp/chef-automate.zip
    dest: /tmp/
    remote_src: true
    mode: "0755"
  register: extract_result
- name: Ensure destination directory exists for Chef Automate CLI
  ansible.builtin.file:
    path: "{{ chef_automate_cli_path | dirname }}"
    state: directory
    mode: "0755"
  become: true
  when: chef_automate_cli_path | dirname != '.'
- name: Move Chef Automate CLI to destination
  ansible.builtin.copy:
    src: /tmp/chef-automate
    dest: "{{ chef_automate_cli_path }}"
    mode: "0755"
    remote_src: true
  become: true
- name: Build product deployment command
  ansible.builtin.set_fact:
    deploy_command: ./chef-automate deploy --accept-terms-and-mlsa={{ chef_automate_accept_terms | lower }}
- name: Add products to deployment command
  ansible.builtin.set_fact:
    deploy_command: "{{ deploy_command }} --product {{ item }}"
  loop: "{{ chef_automate_products }}"
- name: Deploy Chef Automate and/or Chef Infra Server
  ansible.builtin.command:
    cmd: "{{ deploy_command }}"
  become: true
  args:
    creates: /hab
  register: deploy_result
  changed_when: deploy_result.rc == 0
