---
- name: Check if Chef Infra Server is already deployed
  ansible.builtin.command:
    cmd: sudo chef-server-ctl status
  register: server_status
  changed_when: false
  failed_when: false
  ignore_errors: true
- name: Deploy Chef Infra Server only
  ansible.builtin.command:
    cmd: "sudo {{ chef_automate_cli_path }} deploy --product infra-server --accept-terms-and-mlsa={{ chef_automate_accept_terms_and_mlsa | lower }}\n"
  when:
    - server_status.rc != 0
    - chef_automate_deploy_infra_server | bool
    - not chef_automate_deploy_automate | bool
  register: deploy_result
  changed_when: deploy_result.rc == 0
  failed_when:
    - deploy_result.rc != 0
    - "'already deployed' not in deploy_result.stderr"
