---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
- name: Restart Redis
  ansible.builtin.service:
    name: "{{ 'redis-server' if ansible_facts['os_family'] == 'Debian' else 'redis' }}"
    state: restarted
  when: profile_redis_cluster_service_manage | bool
