---
- name: Validate credential variables
  ansible.builtin.include_tasks:
    file: validate_credentials.yml
- name: Include deploy_automate tasks
  ansible.builtin.include_tasks:
    file: deploy_automate.yml
  when: chef_automate_deploy_with_automate | default(true) | bool
- name: Include deploy_chef_server tasks
  ansible.builtin.include_tasks:
    file: deploy_chef_server.yml
  when: chef_automate_deploy_chef_server_only | default(false) | bool
