---
poodle_fix_apache_ssl_config_path: /etc/apache2/mods-available/ssl.conf
poodle_fix_ssl_protocol: -all +TLSv1.2
poodle_fix_apache_service_name: apache2
poodle_fix_ssh_service_name: sshd
poodle_fix_create_backup: true
poodle_fix_validate_config: true
