---
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create {{ chef_user.username }} {{ chef_user.fullname }} {{ chef_user.email }} "{{ chef_user.password }}" --filename {{
      chef_user.filename }}
  become: true
  args:
    creates: "{{ chef_user.filename }}"
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create {{ chef_org.shortname }} "{{ chef_org.fullname }}" --association_user {{ chef_org.association_user }} --filename {{
      chef_org.filename }}
  become: true
  args:
    creates: "{{ chef_org.filename }}"
- name: Verify Chef user creation
  ansible.builtin.stat:
    path: "{{ chef_user.filename }}"
  register: user_pem
- name: Verify Chef organization creation
  ansible.builtin.stat:
    path: "{{ chef_org.filename }}"
  register: org_pem
- name: Display Chef user and organization status
  ansible.builtin.debug:
    msg: "Chef user {{ chef_user.username }}: {{ 'Created' if user_pem.stat.exists else 'Failed' }} Chef organization {{ chef_org.shortname }}: {{ 'Created' if org_pem.stat.exists
      else 'Failed' }}"
