---
chef_automate_cli_path: "{{ ansible_env.HOME }}/chef-automate"
chef_user_key_path: "{{ user_key_path | default(ansible_env.HOME + '/' + username + '.pem') }}"
chef_org_validator_path: "{{ org_validator_path | default(ansible_env.HOME + '/' + org_short_name + '-validator.pem') }}"
chef_automate_configure_system: true
chef_automate_install: true
chef_automate_setup_users_orgs: true
