---
- name: Fix SSL in Apache
  ansible.builtin.replace:
    path: /etc/apache2/mods-available/ssl.conf
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol -all +TLSv1.2
  notify:
    - Restart apache
    - Restart sshd
