---
- name: Ensure Apache and SSH packages are installed
  ansible.builtin.package:
    name:
      - apache2
      - openssh-server
    state: present
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: "{{ apache_ssl_conf_path }}"
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol {{ ssl_protocol_string }}
  notify:
    - Restart apache2
- name: Fix SSH protocol settings
  ansible.builtin.lineinfile:
    path: "{{ ssh_config_path }}"
    regexp: ^Protocol
    line: Protocol 2
    state: present
  notify:
    - Restart sshd
