---
controller_credential_types:
- name: Chef Admin User
  description: Credentials for the initial admin user of Chef Automate and Chef Infra
    Server
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Admin username for Chef Automate and Chef Infra Server
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Admin password for Chef Automate and Chef Infra Server
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
