---
controller_credentials:
- name: Chef User Credentials - automate_deployment
  description: Credential for automate_deployment
  organization: Default
  credential_type: Chef User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    full_name: '{{ full_name }}'
    email: '{{ email }}'
