---
controller_credentials:
- name: FastAPI PostgreSQL Database - fastapi_tutorial
  description: Database credentials for FastAPI application to connect to PostgreSQL
  organization: Default
  credential_type: FastAPI PostgreSQL Database
  update_secrets: true
  inputs:
    db_password: '{{ vault_db_password }}'
    db_username: '{{ db_username }}'
    db_name: '{{ db_name }}'
    db_host: '{{ db_host }}'
    db_port: '{{ db_port }}'
