---
- name: Set hostname for Chef Automate server
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Configure kernel parameters for Chef Automate
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true
  become: true
  loop:
    - name: vm.max_map_count
      value: "{{ chef_automate_vm_max_map_count }}"
    - name: vm.dirty_expire_centisecs
      value: "{{ chef_automate_vm_dirty_expire_centisecs }}"
