---
- name: Ensure Apache is installed
  ansible.builtin.package:
    name: apache2
    state: present
- name: Ensure OpenSSH server is installed
  ansible.builtin.package:
    name: openssh-server
    state: present
- name: Ensure Apache SSL module is enabled
  ansible.builtin.apache2_module:
    name: ssl
    state: present
  notify:
    - Restart apache2
- name: Fix SSL in Apache
  ansible.builtin.replace:
    dest: /etc/apache2/mods-available/ssl.conf
    regexp: ^SSLProtocol.*$
    replace: SSLProtocol -all +TLSv1.2
  notify:
    - Restart apache2
    - Restart sshd
