---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Set vm.max_map_count for optimal Chef Automate performance
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ chef_automate_vm_max_map_count }}"
    state: present
    reload: true
  become: true
- name: Set vm.dirty_expire_centisecs for optimal Chef Automate performance
  ansible.posix.sysctl:
    name: vm.dirty_expire_centisecs
    value: "{{ chef_automate_vm_dirty_expire_centisecs }}"
    state: present
    reload: true
  become: true
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: "{{ chef_automate_cli_path }}.gz"
    mode: "0644"
  become: true
- name: Check if Chef Automate CLI already exists
  ansible.builtin.stat:
    path: "{{ chef_automate_cli_path }}"
  register: chef_automate_cli_stat
  become: true
- name: Extract Chef Automate CLI
  ansible.builtin.shell: gunzip -c {{ chef_automate_cli_path }}.gz > {{ chef_automate_cli_path }}
  args:
    creates: "{{ chef_automate_cli_path }}"
  become: true
  when: not chef_automate_cli_stat.stat.exists
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: "{{ chef_automate_cli_path }}"
    mode: "0755"
  become: true
- name: Deploy Chef Automate and Infra Server
  ansible.builtin.command:
    cmd: "{{ chef_automate_cli_path }} deploy --product automate --product infra-server --accept-terms-and-mlsa=true"
    creates: /hab
  become: true
  tags: molecule-notest
- name: Wait for chef-server-ctl to be available
  ansible.builtin.wait_for:
    path: /usr/bin/chef-server-ctl
    timeout: 300
  become: true
  tags: molecule-notest
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create {{ chef_automate_username }} {{ chef_automate_longusername }} {{ chef_automate_useremail }} "{{ user_password }}"
      --filename {{ chef_automate_userfilename }}
    creates: "{{ chef_automate_userfilename }}"
  become: true
  tags: molecule-notest
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create {{ chef_automate_orgname }} "{{ chef_automate_longorgname }}" --association_user {{ chef_automate_username }} --filename {{
      chef_automate_orgfilename }}
    creates: "{{ chef_automate_orgfilename }}"
  become: true
  tags: molecule-notest
