---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Set vm.max_map_count kernel parameter
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ chef_automate_vm_max_map_count }}"
    state: present
    reload: true
  become: true
- name: Set vm.dirty_expire_centisecs kernel parameter
  ansible.posix.sysctl:
    name: vm.dirty_expire_centisecs
    value: "{{ chef_automate_vm_dirty_expire_centisecs }}"
    state: present
    reload: true
  become: true
- name: Create directory for Chef PEM files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}"
    state: directory
    mode: "0755"
  become: false
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: "{{ chef_automate_cli_path }}"
    mode: "0755"
  register: download_result
- name: Extract Chef Automate CLI (if needed)
  ansible.builtin.shell:
    cmd: gunzip -f {{ chef_automate_cli_path }}
  when: download_result.changed and chef_automate_cli_url.endswith('.gz')
  args:
    creates: "{{ chef_automate_cli_path | regex_replace('\\.gz$', '') }}"
- name: Make Chef Automate CLI executable
  ansible.builtin.file:
    path: "{{ chef_automate_cli_path }}"
    mode: "0755"
    state: file
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: ./chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa=true
  become: true
  args:
    creates: /hab
  register: deploy_result
  changed_when: deploy_result.rc == 0
- name: Create Chef user
  ansible.builtin.command:
    cmd: 'chef-server-ctl user-create  {{ chef_automate_username }}  {{ chef_automate_longusername }}  {{ chef_automate_useremail }}  "{{ user_password }}"  --filename
      {{ ansible_env.HOME }}/{{ chef_automate_userfilename }}

      '
  become: true
  args:
    creates: "{{ ansible_env.HOME }}/{{ chef_automate_userfilename }}"
  register: user_create_result
  changed_when: user_create_result.rc == 0
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: 'chef-server-ctl org-create  {{ chef_automate_orgname }}  "{{ chef_automate_longorgname }}"  --association_user {{ chef_automate_username }}  --filename
      {{ ansible_env.HOME }}/{{ chef_automate_orgfilename }}

      '
  become: true
  args:
    creates: "{{ ansible_env.HOME }}/{{ chef_automate_orgfilename }}"
  register: org_create_result
  changed_when: org_create_result.rc == 0
