---
- name: Check Chef Automate status
  ansible.builtin.command:
    cmd: sudo chef-automate status
  register: chef_automate_status
  changed_when: false
  listen: restart chef-automate
- name: Restart Chef Automate
  ansible.builtin.command:
    cmd: sudo chef-automate restart
  listen: restart chef-automate
  changed_when: false
  when: chef_automate_status.rc == 0
- name: Check Chef Infra Server status
  ansible.builtin.command:
    cmd: sudo chef-server-ctl status
  register: chef_server_status
  changed_when: false
  listen: restart chef-server
- name: Restart Chef Infra Server
  ansible.builtin.command:
    cmd: sudo chef-server-ctl restart
  listen: restart chef-server
  changed_when: false
  when: chef_server_status.rc == 0
