- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: '{{ chef_automate_cli_url }}'
    dest: '{{ chef_automate_cli_path }}.zip'
    mode: '0644'
- name: Check if Chef Automate CLI already exists
  ansible.builtin.stat:
    path: '{{ chef_automate_cli_path }}'
  register: chef_automate_cli_stat
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip -c {{ chef_automate_cli_path }}.zip > {{ chef_automate_cli_path }} && chmod +x {{ chef_automate_cli_path }}
    creates: '{{ chef_automate_cli_path }}'
  when: not chef_automate_cli_stat.stat.exists
- name: Deploy Chef Automate with Chef Infra Server
  ansible.builtin.command:
    cmd: './chef-automate deploy  --product automate  --product infra-server  --accept-terms-and-mlsa={{ chef_automate_accept_terms | lower }} '
  args:
    creates: /hab
  become: true
