---
chef_automate_hostname: automate.chef.lab
chef_automate_cli_url: https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip
chef_automate_accept_terms: true
chef_user_key_path: "{{ private_key_path | default('~/') }}"
chef_org_validator_key_path: "{{ validator_key_path | default('~/') }}"
chef_org_name: "{{ org_name | default('lab') }}"
chef_org_full_name: "{{ org_full_name | default('Chef Lab') }}"
