---
hostname: automate.chef.lab
orgname: lab
longorgname: Chef Lab
vm_max_map_count: 262144
vm_dirty_expire_centisecs: 20000
accept_terms_and_mlsa: true
deploy_automate: true
deploy_infra_server: true
chef_automate_binary_path: ./chef-automate
