---
- name: Validate credential variables
  ansible.builtin.include_tasks: validate_credentials.yml
- name: Include website HTTPS tasks
  ansible.builtin.include_tasks: website_https.yml
- name: Include POODLE fix tasks
  ansible.builtin.include_tasks: poodle_fix.yml
