---
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip -c {{ chef_automate_cli_path }}.gz > {{ chef_automate_cli_path }}
  args:
    creates: "{{ chef_automate_cli_path }}"
- name: Wait for Chef Automate services
  ansible.builtin.pause:
    seconds: 30
  listen: Wait for Chef Automate services
- name: Wait for Chef Infra Server services
  ansible.builtin.pause:
    seconds: 30
  listen: Wait for Chef Infra Server services
