---
- name: Check if Chef Automate is already deployed
  ansible.builtin.stat:
    path: /hab/sup/default/data/services.dat
  register: chef_automate_deployed
  become: true
- name: Deploy Chef Automate and Infra Server
  ansible.builtin.command:
    cmd: "{{ chef_automate_cli_path }} deploy  --product automate  --product infra-server  --accept-terms-and-mlsa={{ chef_accept_license | lower }}\n"
    creates: /hab/sup/default/data/services.dat
  become: true
  when: not chef_automate_deployed.stat.exists
  notify: Wait for Chef services to be ready
