---
controller_credentials:
- name: FastAPI PostgreSQL Database - fastapi_tutorial
  description: PostgreSQL database credentials for FastAPI application
  organization: Default
  credential_type: FastAPI PostgreSQL Database
  update_secrets: true
  inputs:
    db_password: '{{ vault_db_password }}'
