---
- name: Include website HTTPS setup tasks
  ansible.builtin.include_tasks: website_https.yml
- name: Include POODLE vulnerability fix tasks
  ansible.builtin.include_tasks: poodle_fix.yml
- name: Configure SSH security
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
    state: present
  notify: Restart sshd
