---
automate_hostname: automate.chef.lab
automate_vm_max_map_count: 262144
automate_vm_dirty_expire_centisecs: 20000
automate_cli_url: https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip
automate_cli_path: /tmp/chef-automate
automate_accept_terms: true
organization_short_name: lab
organization_full_name: Chef Lab
user_pem_path: /tmp/{{ username }}.pem
org_validator_pem_path: /tmp/{{ organization_short_name }}-validator.pem
