---
controller_credentials:
- name: Chef User Credentials - chef_deployment
  description: Credential for chef_deployment
  organization: Default
  credential_type: Chef User Credentials
  update_secrets: true
  inputs:
    username: '{{ username }}'
    user_password: '{{ vault_user_password }}'
    user_email: '{{ user_email }}'
    long_username: '{{ long_username }}'
- name: Chef Organization Configuration - chef_deployment
  description: Credential for chef_deployment
  organization: Default
  credential_type: Chef Organization Configuration
  update_secrets: true
  inputs:
    org_name: '{{ org_name }}'
    long_org_name: '{{ long_org_name }}'
