---
controller_credential_types:
- name: Chef Server Credentials
  description: Credentials used for Chef Server deployment
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for Chef Server authentication
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef Server authentication
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
- name: Chef Automate Credentials
  description: Credentials used for Chef Automate deployment
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username for Chef Automate authentication
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for Chef Automate authentication
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
