---
- name: Create Chef user
  ansible.builtin.command:
    cmd: chef-server-ctl user-create {{ username }} "{{ user_full_name }}" {{ user_email }} "{{ user_password }}" --filename {{ chef_automate_user_pem_path }}
  become: true
  args:
    creates: "{{ chef_automate_user_pem_path }}"
  register: chef_user_create
  changed_when: chef_user_create.rc == 0
  no_log: true
- name: Create Chef organization
  ansible.builtin.command:
    cmd: chef-server-ctl org-create {{ org_name }} "{{ org_full_name }}" --association_user {{ username }} --filename {{ chef_automate_org_validator_pem_path }}
  become: true
  args:
    creates: "{{ chef_automate_org_validator_pem_path }}"
  register: chef_org_create
  changed_when: chef_org_create.rc == 0
- name: Check if user PEM file exists
  ansible.builtin.stat:
    path: "{{ chef_automate_user_pem_path }}"
  register: user_pem_file
  when: user_pem is defined and user_pem | length > 0
- name: Save user PEM file content
  ansible.builtin.copy:
    content: "{{ user_pem }}"
    dest: "{{ chef_automate_user_pem_path }}"
    mode: "0600"
  when: user_pem is defined and user_pem | length > 0 and (not user_pem_file.stat.exists or user_pem_file.stat.size == 0)
- name: Check if organization validator PEM file exists
  ansible.builtin.stat:
    path: "{{ chef_automate_org_validator_pem_path }}"
  register: org_validator_pem_file
  when: org_validator_pem is defined and org_validator_pem | length > 0
- name: Save organization validator PEM file content
  ansible.builtin.copy:
    content: "{{ org_validator_pem }}"
    dest: "{{ chef_automate_org_validator_pem_path }}"
    mode: "0600"
  when: org_validator_pem is defined and org_validator_pem | length > 0 and (not org_validator_pem_file.stat.exists or org_validator_pem_file.stat.size == 0)
