---
apache_version: 2.4.41-4ubuntu3.10
apache_ssl_cert_path: /etc/apache2/certs/apache.crt
apache_ssl_key_path: /etc/apache2/certs/apache.key
apache_ssl_csr_path: /etc/apache2/certs/apache.csr
apache_ssl_protocol: -all +TLSv1.2
website_root: /var/www/helloworld
website_vhost_name: helloworld
