---
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: "{{ chef_automate_cli_url }}"
    dest: /tmp/chef-automate_linux_amd64.zip
    mode: "0644"
  register: download_result
  notify:
    - Extract Chef Automate CLI
    - Make Chef Automate CLI executable
- name: Deploy Chef Infra Server only
  ansible.builtin.command:
    cmd: "{{ chef_automate_cli_path }} deploy --product infra-server --accept-terms-and-mlsa={{ accept_terms_and_mlsa | lower }}"
  args:
    creates: /hab
  become: true
  when: not deploy_automate | bool
